import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

type LanguageCode = 'en' | 'de' | 'bs' | 'hr' | 'sr' | 'es' | 'fr' | 'it';
type TranslationDictionary = Record<string, Record<LanguageCode, string>>;

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  readonly languages = [
    { code: 'en', name: 'English' },
    { code: 'de', name: 'Deutsch' },
    { code: 'bs', name: 'Bosanski' },
    { code: 'hr', name: 'Hrvatski' },
    { code: 'sr', name: 'Srpski' },
    { code: 'es', name: 'Espanol' },
    { code: 'fr', name: 'Francais' },
    { code: 'it', name: 'Italiano' },
  ];

  private readonly defaultLanguage: LanguageCode = 'bs';
  private readonly languageSubject = new BehaviorSubject<LanguageCode>(
    this.getSavedLanguage(),
  );

  readonly language$ = this.languageSubject.asObservable();

  private readonly translations: TranslationDictionary = {
    appTitle: {
      en: 'Sports booking',
      de: 'Sporttermin-Reservierung',
      bs: 'Rezervacija sportskih termina',
      hr: 'Rezervacija sportskih termina',
      sr: 'Rezervacija sportskih termina',
      es: 'Reserva de pistas deportivas',
      fr: 'Reservation de terrains sportifs',
      it: 'Prenotazione campi sportivi',
    },
    home: {
      en: 'Home',
      de: 'Startseite',
      bs: 'Početna',
      hr: 'Početna',
      sr: 'Početna',
      es: 'Inicio',
      fr: 'Accueil',
      it: 'Home',
    },
    sportsFields: {
      en: 'Sports fields',
      de: 'Sportplaetze',
      bs: 'Sportski tereni',
      hr: 'Sportski tereni',
      sr: 'Sportski tereni',
      es: 'Campos deportivos',
      fr: 'Terrains sportifs',
      it: 'Campi sportivi',
    },
    users: {
      en: 'Users',
      de: 'Benutzer',
      bs: 'Korisnici',
      hr: 'Korisnici',
      sr: 'Korisnici',
      es: 'Usuarios',
      fr: 'Utilisateurs',
      it: 'Utenti',
    },
    groups: {
      en: 'Groups',
      de: 'Gruppen',
      bs: 'Grupe',
      hr: 'Grupe',
      sr: 'Grupe',
      es: 'Grupos',
      fr: 'Groupes',
      it: 'Gruppi',
    },
    welcome: {
      en: 'Welcome',
      de: 'Willkommen',
      bs: 'Dobrodošli',
      hr: 'Dobrodošli',
      sr: 'Dobrodošli',
      es: 'Bienvenido',
      fr: 'Bienvenue',
      it: 'Benvenuto',
    },
    profile: {
      en: 'Profile',
      de: 'Profil',
      bs: 'Profil',
      hr: 'Profil',
      sr: 'Profil',
      es: 'Perfil',
      fr: 'Profil',
      it: 'Profilo',
    },
    settings: {
      en: 'Settings',
      de: 'Einstellungen',
      bs: 'Postavke',
      hr: 'Postavke',
      sr: 'Podešavanja',
      es: 'Configuracion',
      fr: 'Parametres',
      it: 'Impostazioni',
    },
    logout: {
      en: 'Logout',
      de: 'Abmelden',
      bs: 'Odjava',
      hr: 'Odjava',
      sr: 'Odjava',
      es: 'Cerrar sesion',
      fr: 'Deconnexion',
      it: 'Esci',
    },
    login: {
      en: 'Login',
      de: 'Anmelden',
      bs: 'Prijava',
      hr: 'Prijava',
      sr: 'Prijava',
      es: 'Iniciar sesion',
      fr: 'Connexion',
      it: 'Accesso',
    },
    register: {
      en: 'Register',
      de: 'Registrieren',
      bs: 'Registracija',
      hr: 'Registracija',
      sr: 'Registracija',
      es: 'Registro',
      fr: 'Inscription',
      it: 'Registrazione',
    },
    username: {
      en: 'Username',
      de: 'Benutzername',
      bs: 'Korisničko ime',
      hr: 'Korisničko ime',
      sr: 'Korisničko ime',
      es: 'Nombre de usuario',
      fr: 'Nom utilisateur',
      it: 'Nome utente',
    },
    password: {
      en: 'Password',
      de: 'Passwort',
      bs: 'Lozinka',
      hr: 'Lozinka',
      sr: 'Lozinka',
      es: 'Contrasena',
      fr: 'Mot de passe',
      it: 'Password',
    },
    fullName: {
      en: 'Full name',
      de: 'Vor- und Nachname',
      bs: 'Ime i prezime',
      hr: 'Ime i prezime',
      sr: 'Ime i prezime',
      es: 'Nombre completo',
      fr: 'Nom complet',
      it: 'Nome completo',
    },
    email: {
      en: 'Email',
      de: 'E-Mail',
      bs: 'Email',
      hr: 'Email',
      sr: 'Email',
      es: 'Email',
      fr: 'Email',
      it: 'Email',
    },
    phone: {
      en: 'Phone',
      de: 'Telefon',
      bs: 'Telefon',
      hr: 'Telefon',
      sr: 'Telefon',
      es: 'Telefono',
      fr: 'Telephone',
      it: 'Telefono',
    },
    phoneNumber: {
      en: 'Phone number',
      de: 'Telefonnummer',
      bs: 'Broj telefona',
      hr: 'Broj telefona',
      sr: 'Broj telefona',
      es: 'Numero de telefono',
      fr: 'Numero de telephone',
      it: 'Numero di telefono',
    },
    requiredField: {
      en: 'This field is required',
      de: 'Dieses Feld ist erforderlich',
      bs: 'Ovo polje je obavezno',
      hr: 'Ovo polje je obavezno',
      sr: 'Ovo polje je obavezno',
      es: 'Este campo es obligatorio',
      fr: 'Ce champ est obligatoire',
      it: 'Questo campo e obbligatorio',
    },
    invalidEmail: {
      en: 'Invalid email',
      de: 'Ungueltige E-Mail',
      bs: 'Nevalidan e-mail',
      hr: 'Neispravan e-mail',
      sr: 'Nevalidan e-mail',
      es: 'Email invalido',
      fr: 'Email invalide',
      it: 'Email non valida',
    },
    invalidPhone: {
      en: 'Invalid phone number',
      de: 'Ungueltige Telefonnummer',
      bs: 'Nevalidan broj telefona',
      hr: 'Neispravan broj telefona',
      sr: 'Nevalidan broj telefona',
      es: 'Telefono invalido',
      fr: 'Telephone invalide',
      it: 'Telefono non valido',
    },
    emailTaken: {
      en: 'Email is already in use',
      de: 'E-Mail wird bereits verwendet',
      bs: 'E-mail je već u upotrebi',
      hr: 'E-mail je već u upotrebi',
      sr: 'E-mail je već u upotrebi',
      es: 'El email ya esta en uso',
      fr: 'Email deja utilise',
      it: 'Email gia in uso',
    },
    phoneTaken: {
      en: 'Phone number is already in use',
      de: 'Telefonnummer wird bereits verwendet',
      bs: 'Broj telefona je već u upotrebi',
      hr: 'Broj telefona je već u upotrebi',
      sr: 'Broj telefona je već u upotrebi',
      es: 'El telefono ya esta en uso',
      fr: 'Telephone deja utilise',
      it: 'Telefono gia in uso',
    },
    usernameTaken: {
      en: 'Username is already in use',
      de: 'Benutzername wird bereits verwendet',
      bs: 'Korisničko ime je već u upotrebi',
      hr: 'Korisničko ime je već u upotrebi',
      sr: 'Korisničko ime je već u upotrebi',
      es: 'El usuario ya esta en uso',
      fr: 'Nom utilisateur deja utilise',
      it: 'Nome utente gia in uso',
    },
    invalidLogin: {
      en: 'Invalid username or password',
      de: 'Ungueltiger Benutzername oder Passwort',
      bs: 'Nevalidno korisničko ime ili lozinka',
      hr: 'Neispravno korisničko ime ili lozinka',
      sr: 'Nevalidno korisničko ime ili lozinka',
      es: 'Usuario o contrasena invalidos',
      fr: 'Identifiant ou mot de passe invalide',
      it: 'Nome utente o password non validi',
    },
    noProfile: {
      en: "Don't have a profile?",
      de: 'Noch kein Profil?',
      bs: 'Nemate profil?',
      hr: 'Nemate profil?',
      sr: 'Nemate profil?',
      es: 'No tienes perfil?',
      fr: 'Vous navez pas de profil?',
      it: 'Non hai un profilo?',
    },
    haveProfile: {
      en: 'Already have a profile?',
      de: 'Haben Sie bereits ein Profil?',
      bs: 'Već imate profil?',
      hr: 'Već imate profil?',
      sr: 'Već imate profil?',
      es: 'Ya tienes perfil?',
      fr: 'Vous avez deja un profil?',
      it: 'Hai gia un profilo?',
    },
    notifications: {
      en: 'Notifications',
      de: 'Benachrichtigungen',
      bs: 'Obavijesti',
      hr: 'Obavijesti',
      sr: 'Obaveštenja',
      es: 'Notificaciones',
      fr: 'Notifications',
      it: 'Notifiche',
    },
    noNotifications: {
      en: 'No notifications',
      de: 'Keine Benachrichtigungen',
      bs: 'Nema obavijesti',
      hr: 'Nema obavijesti',
      sr: 'Nema obaveštenja',
      es: 'No hay notificaciones',
      fr: 'Aucune notification',
      it: 'Nessuna notifica',
    },
    justNow: {
      en: 'Just now',
      de: 'Gerade eben',
      bs: 'Upravo sada',
      hr: 'Upravo sada',
      sr: 'Upravo sada',
      es: 'Ahora mismo',
      fr: 'A l instant',
      it: 'Adesso',
    },
    minutesAgo: {
      en: '{count}min ago',
      de: 'vor {count} Min.',
      bs: 'prije {count} min',
      hr: 'prije {count} min',
      sr: 'pre {count} min',
      es: 'hace {count} min',
      fr: 'il y a {count} min',
      it: '{count} min fa',
    },
    hoursAgo: {
      en: '{count}hr ago',
      de: 'vor {count} Std.',
      bs: 'prije {count} h',
      hr: 'prije {count} h',
      sr: 'pre {count} h',
      es: 'hace {count} h',
      fr: 'il y a {count} h',
      it: '{count} h fa',
    },
    daysAgo: {
      en: '{count}d ago',
      de: 'vor {count} T.',
      bs: 'prije {count} d',
      hr: 'prije {count} d',
      sr: 'pre {count} d',
      es: 'hace {count} d',
      fr: 'il y a {count} j',
      it: '{count} g fa',
    },
    invitationReceivedNotification: {
      en: 'You have been invited to group {groupName}',
      de: 'Sie wurden zur Gruppe {groupName} eingeladen',
      bs: 'Pozvani ste u grupu {groupName}',
      hr: 'Pozvani ste u grupu {groupName}',
      sr: 'Pozvani ste u grupu {groupName}',
      es: 'Te invitaron al grupo {groupName}',
      fr: 'Vous avez ete invite au groupe {groupName}',
      it: 'Sei stato invitato al gruppo {groupName}',
    },
    invitationAcceptedNotification: {
      en: '{userName} accepted the invitation for group {groupName}',
      de: '{userName} hat die Einladung fuer Gruppe {groupName} angenommen',
      bs: '{userName} je prihvatio poziv za grupu {groupName}',
      hr: '{userName} je prihvatio poziv za grupu {groupName}',
      sr: '{userName} je prihvatio poziv za grupu {groupName}',
      es: '{userName} acepto la invitacion para el grupo {groupName}',
      fr: '{userName} a accepte invitation pour le groupe {groupName}',
      it: '{userName} ha accettato invito per il gruppo {groupName}',
    },
    joinRequestReceivedNotification: {
      en: '{userName} requested access to group {groupName}',
      de: '{userName} hat Zugang zur Gruppe {groupName} angefragt',
      bs: '{userName} je zatražio pristup grupi {groupName}',
      hr: '{userName} je zatražio pristup grupi {groupName}',
      sr: '{userName} je zatražio pristup grupi {groupName}',
      es: '{userName} solicito acceso al grupo {groupName}',
      fr: '{userName} a demande acces au groupe {groupName}',
      it: '{userName} ha richiesto accesso al gruppo {groupName}',
    },
    joinRequestAcceptedNotification: {
      en: 'Your request to join group {groupName} was accepted',
      de: 'Ihre Anfrage zur Gruppe {groupName} wurde angenommen',
      bs: 'Vaš zahtjev za pristup grupi {groupName} je prihvaćen',
      hr: 'Vaš zahtjev za pristup grupi {groupName} je prihvaćen',
      sr: 'Vaš zahtjev za pristup grupi {groupName} je prihvaćen',
      es: 'Tu solicitud para el grupo {groupName} fue aceptada',
      fr: 'Votre demande pour le groupe {groupName} a ete acceptee',
      it: 'La tua richiesta per il gruppo {groupName} e stata accettata',
    },
    accept: {
      en: 'Accept',
      de: 'Annehmen',
      bs: 'Prihvati',
      hr: 'Prihvati',
      sr: 'Prihvati',
      es: 'Aceptar',
      fr: 'Accepter',
      it: 'Accetta',
    },
    decline: {
      en: 'Decline',
      de: 'Ablehnen',
      bs: 'Odbij',
      hr: 'Odbij',
      sr: 'Odbij',
      es: 'Rechazar',
      fr: 'Refuser',
      it: 'Rifiuta',
    },
    invitationAccepted: {
      en: 'Invitation accepted',
      de: 'Einladung angenommen',
      bs: 'Poziv prihvaćen',
      hr: 'Poziv prihvaćen',
      sr: 'Poziv prihvaćen',
      es: 'Invitacion aceptada',
      fr: 'Invitation acceptee',
      it: 'Invito accettato',
    },
    invitationDeclined: {
      en: 'Invitation declined',
      de: 'Einladung abgelehnt',
      bs: 'Poziv odbijen',
      hr: 'Poziv odbijen',
      sr: 'Poziv odbijen',
      es: 'Invitacion rechazada',
      fr: 'Invitation refusee',
      it: 'Invito rifiutato',
    },
    acceptInvitation: {
      en: 'Accept invitation',
      de: 'Einladung annehmen',
      bs: 'Prihvati pozivnicu',
      hr: 'Prihvati pozivnicu',
      sr: 'Prihvati pozivnicu',
      es: 'Aceptar invitacion',
      fr: 'Accepter invitation',
      it: 'Accetta invito',
    },
    declineInvitation: {
      en: 'Decline invitation',
      de: 'Einladung ablehnen',
      bs: 'Odbij pozivnicu',
      hr: 'Odbij pozivnicu',
      sr: 'Odbij pozivnicu',
      es: 'Rechazar invitacion',
      fr: 'Refuser invitation',
      it: 'Rifiuta invito',
    },
    acceptJoinRequest: {
      en: 'Accept request',
      de: 'Anfrage annehmen',
      bs: 'Prihvati zahtjev',
      hr: 'Prihvati zahtjev',
      sr: 'Prihvati zahtjev',
      es: 'Aceptar solicitud',
      fr: 'Accepter la demande',
      it: 'Accetta richiesta',
    },
    declineJoinRequest: {
      en: 'Decline request',
      de: 'Anfrage ablehnen',
      bs: 'Odbij zahtjev',
      hr: 'Odbij zahtjev',
      sr: 'Odbij zahtjev',
      es: 'Rechazar solicitud',
      fr: 'Refuser la demande',
      it: 'Rifiuta richiesta',
    },
    joinRequestAccepted: {
      en: 'Request accepted',
      de: 'Anfrage angenommen',
      bs: 'Zahtjev prihvaćen',
      hr: 'Zahtjev prihvaćen',
      sr: 'Zahtjev prihvaćen',
      es: 'Solicitud aceptada',
      fr: 'Demande acceptee',
      it: 'Richiesta accettata',
    },
    joinRequestDeclined: {
      en: 'Request declined',
      de: 'Anfrage abgelehnt',
      bs: 'Zahtjev odbijen',
      hr: 'Zahtjev odbijen',
      sr: 'Zahtjev odbijen',
      es: 'Solicitud rechazada',
      fr: 'Demande refusee',
      it: 'Richiesta rifiutata',
    },
    joinRequestResponseError: {
      en: 'Error responding to join request.',
      de: 'Fehler beim Beantworten der Beitrittsanfrage.',
      bs: 'Greška pri odgovoru na zahtjev.',
      hr: 'Greška pri odgovoru na zahtjev.',
      sr: 'Greška pri odgovoru na zahtjev.',
      es: 'Error al responder la solicitud.',
      fr: 'Erreur lors de la reponse a la demande.',
      it: 'Errore durante risposta alla richiesta.',
    },
    invitationResponseError: {
      en: 'Error responding to invitation.',
      de: 'Fehler beim Beantworten der Einladung.',
      bs: 'Greška pri odgovoru na pozivnicu.',
      hr: 'Greška pri odgovoru na pozivnicu.',
      sr: 'Greška pri odgovoru na pozivnicu.',
      es: 'Error al responder la invitacion.',
      fr: 'Erreur lors de la reponse a invitation.',
      it: 'Errore durante risposta invito.',
    },
    receiveEmailNotifications: {
      en: 'Receive email notifications',
      de: 'E-Mail-Benachrichtigungen erhalten',
      bs: 'Primaj email obavijesti',
      hr: 'Primaj email obavijesti',
      sr: 'Primaj email obaveštenja',
      es: 'Recibir notificaciones por email',
      fr: 'Recevoir des notifications par email',
      it: 'Ricevi notifiche email',
    },
    appearance: {
      en: 'Appearance',
      de: 'Darstellung',
      bs: 'Izgled',
      hr: 'Izgled',
      sr: 'Izgled',
      es: 'Apariencia',
      fr: 'Apparence',
      it: 'Aspetto',
    },
    darkMode: {
      en: 'Dark mode',
      de: 'Dunkler Modus',
      bs: 'Tamni mod',
      hr: 'Tamni mod',
      sr: 'Tamni režim',
      es: 'Modo oscuro',
      fr: 'Mode sombre',
      it: 'Modalita scura',
    },
    appLanguage: {
      en: 'App language',
      de: 'App-Sprache',
      bs: 'Jezik aplikacije',
      hr: 'Jezik aplikacije',
      sr: 'Jezik aplikacije',
      es: 'Idioma de la aplicacion',
      fr: 'Langue de application',
      it: 'Lingua app',
    },
    selectedLanguage: {
      en: 'Selected language',
      de: 'Ausgewaehlte Sprache',
      bs: 'Odabrani jezik',
      hr: 'Odabrani jezik',
      sr: 'Odabrani jezik',
      es: 'Idioma seleccionado',
      fr: 'Langue selectionnee',
      it: 'Lingua selezionata',
    },
    currentLanguage: {
      en: 'Current language',
      de: 'Aktuelle Sprache',
      bs: 'Trenutno odabrani jezik',
      hr: 'Trenutno odabrani jezik',
      sr: 'Trenutno odabrani jezik',
      es: 'Idioma actual',
      fr: 'Langue actuelle',
      it: 'Lingua attuale',
    },
    languageSaved: {
      en: 'App language saved.',
      de: 'App-Sprache gespeichert.',
      bs: 'Jezik aplikacije je sačuvan.',
      hr: 'Jezik aplikacije je spremljen.',
      sr: 'Jezik aplikacije je sačuvan.',
      es: 'Idioma guardado.',
      fr: 'Langue enregistree.',
      it: 'Lingua salvata.',
    },
    account: {
      en: 'Account',
      de: 'Konto',
      bs: 'Račun',
      hr: 'Račun',
      sr: 'Nalog',
      es: 'Cuenta',
      fr: 'Compte',
      it: 'Account',
    },
    accountInfo: {
      en: 'Account information',
      de: 'Kontoinformationen',
      bs: 'Informacije o računu',
      hr: 'Informacije o računu',
      sr: 'Informacije o nalogu',
      es: 'Informacion de la cuenta',
      fr: 'Informations du compte',
      it: 'Informazioni account',
    },
    changeUsername: {
      en: 'Change username',
      de: 'Benutzername aendern',
      bs: 'Promijeni korisničko ime',
      hr: 'Promijeni korisničko ime',
      sr: 'Promeni korisničko ime',
      es: 'Cambiar usuario',
      fr: 'Changer le nom utilisateur',
      it: 'Cambia nome utente',
    },
    logoutAllDevices: {
      en: 'Logout from all devices',
      de: 'Von allen Geraeten abmelden',
      bs: 'Odjavi sa svih uređaja',
      hr: 'Odjavi sa svih uređaja',
      sr: 'Odjavi se sa svih uređaja',
      es: 'Cerrar sesion en todos los dispositivos',
      fr: 'Se deconnecter de tous les appareils',
      it: 'Esci da tutti i dispositivi',
    },
    notSet: {
      en: 'Not set',
      de: 'Nicht festgelegt',
      bs: 'Nije postavljeno',
      hr: 'Nije postavljeno',
      sr: 'Nije postavljeno',
      es: 'No configurado',
      fr: 'Non defini',
      it: 'Non impostato',
    },
    settingsLoadError: {
      en: 'Error loading settings.',
      de: 'Fehler beim Laden der Einstellungen.',
      bs: 'Greška pri učitavanju postavki.',
      hr: 'Greška pri učitavanju postavki.',
      sr: 'Greška pri učitavanju podešavanja.',
      es: 'Error al cargar la configuracion.',
      fr: 'Erreur lors du chargement des parametres.',
      it: 'Errore durante il caricamento impostazioni.',
    },
    notificationsSaved: {
      en: 'Notification settings saved.',
      de: 'Benachrichtigungseinstellungen gespeichert.',
      bs: 'Postavke obavijesti su sačuvane.',
      hr: 'Postavke obavijesti su spremljene.',
      sr: 'Podešavanja obaveštenja su sačuvana.',
      es: 'Notificaciones guardadas.',
      fr: 'Notifications enregistrees.',
      it: 'Notifiche salvate.',
    },
    notificationsSaveError: {
      en: 'Error saving notification settings.',
      de: 'Fehler beim Speichern der Benachrichtigungen.',
      bs: 'Greška pri spremanju postavki obavijesti.',
      hr: 'Greška pri spremanju postavki obavijesti.',
      sr: 'Greška pri čuvanju obaveštenja.',
      es: 'Error al guardar notificaciones.',
      fr: 'Erreur lors de enregistrement.',
      it: 'Errore durante il salvataggio.',
    },
    usernameRequired: {
      en: 'Username is required.',
      de: 'Benutzername ist erforderlich.',
      bs: 'Korisničko ime je obavezno.',
      hr: 'Korisničko ime je obavezno.',
      sr: 'Korisničko ime je obavezno.',
      es: 'El usuario es obligatorio.',
      fr: 'Nom utilisateur obligatoire.',
      it: 'Nome utente obbligatorio.',
    },
    usernameChanged: {
      en: 'Username changed successfully.',
      de: 'Benutzername erfolgreich geaendert.',
      bs: 'Korisničko ime je uspješno promijenjeno.',
      hr: 'Korisničko ime je uspješno promijenjeno.',
      sr: 'Korisničko ime je uspešno promenjeno.',
      es: 'Usuario cambiado correctamente.',
      fr: 'Nom utilisateur modifie.',
      it: 'Nome utente modificato.',
    },
    usernameChangeError: {
      en: 'Error changing username.',
      de: 'Fehler beim Aendern des Benutzernamens.',
      bs: 'Greška pri promjeni korisničkog imena.',
      hr: 'Greška pri promjeni korisničkog imena.',
      sr: 'Greška pri promeni korisničkog imena.',
      es: 'Error al cambiar usuario.',
      fr: 'Erreur lors du changement.',
      it: 'Errore durante la modifica.',
    },
    usernameTooShort: {
      en: 'Username is too short',
      de: 'Benutzername ist zu kurz',
      bs: 'Korisničko ime je nedovoljno dugo',
      hr: 'Korisničko ime je prekratko',
      sr: 'Korisničko ime je prekratko',
      es: 'El usuario es demasiado corto',
      fr: 'Nom utilisateur trop court',
      it: 'Nome utente troppo corto',
    },
    usernameNoSpaces: {
      en: 'Username cannot contain spaces',
      de: 'Benutzername darf keine Leerzeichen enthalten',
      bs: 'Korisničko ime ne smije sadržavati razmake',
      hr: 'Korisničko ime ne smije sadržavati razmake',
      sr: 'Korisničko ime ne sme sadržavati razmake',
      es: 'El usuario no puede contener espacios',
      fr: 'Nom utilisateur sans espaces',
      it: 'Nome utente senza spazi',
    },
    passwordTooShort: {
      en: 'Password is too short',
      de: 'Passwort ist zu kurz',
      bs: 'Lozinka je nedovoljno duga',
      hr: 'Lozinka je prekratka',
      sr: 'Lozinka je prekratka',
      es: 'La contrasena es demasiado corta',
      fr: 'Mot de passe trop court',
      it: 'Password troppo corta',
    },
    passwordStrength: {
      en: 'Password cannot contain spaces and must include a letter, number, and special character',
      de: 'Passwort darf keine Leerzeichen enthalten und muss Buchstaben, Zahlen und Sonderzeichen enthalten',
      bs: 'Lozinka ne smije imati razmake i mora sadržavati slovo, broj i specijalni znak',
      hr: 'Lozinka ne smije imati razmake i mora sadržavati slovo, broj i poseban znak',
      sr: 'Lozinka ne sme imati razmake i mora sadržavati slovo, broj i specijalni znak',
      es: 'La contrasena no puede contener espacios y debe incluir letra, numero y caracter especial',
      fr: 'Mot de passe sans espaces avec lettre, chiffre et caractere special',
      it: 'Password senza spazi con lettera, numero e carattere speciale',
    },
    cancel: {
      en: 'Cancel',
      de: 'Abbrechen',
      bs: 'Otkaži',
      hr: 'Otkaži',
      sr: 'Otkaži',
      es: 'Cancelar',
      fr: 'Annuler',
      it: 'Annulla',
    },
    confirm: {
      en: 'Confirm',
      de: 'Bestaetigen',
      bs: 'Potvrdi',
      hr: 'Potvrdi',
      sr: 'Potvrdi',
      es: 'Confirmar',
      fr: 'Confirmer',
      it: 'Conferma',
    },
    edit: {
      en: 'Edit',
      de: 'Bearbeiten',
      bs: 'Uredi',
      hr: 'Uredi',
      sr: 'Uredi',
      es: 'Editar',
      fr: 'Modifier',
      it: 'Modifica',
    },
    editProfile: {
      en: 'Edit profile',
      de: 'Profil bearbeiten',
      bs: 'Uredi profil',
      hr: 'Uredi profil',
      sr: 'Uredi profil',
      es: 'Editar perfil',
      fr: 'Modifier le profil',
      it: 'Modifica profilo',
    },
    profilePicture: {
      en: 'Profile picture',
      de: 'Profilbild',
      bs: 'Profilna slika',
      hr: 'Profilna slika',
      sr: 'Profilna slika',
      es: 'Foto de perfil',
      fr: 'Photo de profil',
      it: 'Foto profilo',
    },
    removeProfilePicture: {
      en: 'Remove profile picture',
      de: 'Profilbild entfernen',
      bs: 'Ukloni profilnu sliku',
      hr: 'Ukloni profilnu sliku',
      sr: 'Ukloni profilnu sliku',
      es: 'Eliminar foto de perfil',
      fr: 'Supprimer la photo de profil',
      it: 'Rimuovi foto profilo',
    },
    location: {
      en: 'Location',
      de: 'Ort',
      bs: 'Lokacija',
      hr: 'Lokacija',
      sr: 'Lokacija',
      es: 'Ubicacion',
      fr: 'Emplacement',
      it: 'Posizione',
    },
    enterFullName: {
      en: 'Enter full name',
      de: 'Vor- und Nachname eingeben',
      bs: 'Unesite ime i prezime',
      hr: 'Unesite ime i prezime',
      sr: 'Unesite ime i prezime',
      es: 'Introduce el nombre completo',
      fr: 'Saisir le nom complet',
      it: 'Inserisci nome completo',
    },
    enterCity: {
      en: 'Enter city',
      de: 'Stadt eingeben',
      bs: 'Unesite grad',
      hr: 'Unesite grad',
      sr: 'Unesite grad',
      es: 'Introduce ciudad',
      fr: 'Saisir la ville',
      it: 'Inserisci citta',
    },
    wrongPhoneFormat: {
      en: 'Wrong phone number format.',
      de: 'Falsches Telefonnummerformat.',
      bs: 'Pogrešan format broja.',
      hr: 'Pogrešan format broja.',
      sr: 'Pogrešan format broja.',
      es: 'Formato de telefono incorrecto.',
      fr: 'Format de telephone incorrect.',
      it: 'Formato telefono errato.',
    },
    saveChanges: {
      en: 'Save changes',
      de: 'Aenderungen speichern',
      bs: 'Spremi promjene',
      hr: 'Spremi promjene',
      sr: 'Sačuvaj promene',
      es: 'Guardar cambios',
      fr: 'Enregistrer',
      it: 'Salva modifiche',
    },
    profileUpdated: {
      en: 'Profile updated successfully.',
      de: 'Profil erfolgreich aktualisiert.',
      bs: 'Profil je uspješno ažuriran.',
      hr: 'Profil je uspješno ažuriran.',
      sr: 'Profil je uspešno ažuriran.',
      es: 'Perfil actualizado correctamente.',
      fr: 'Profil mis a jour.',
      it: 'Profilo aggiornato.',
    },
    selectValidImage: {
      en: 'Select a valid image.',
      de: 'Waehlen Sie ein gueltiges Bild.',
      bs: 'Odaberite validnu sliku.',
      hr: 'Odaberite validnu sliku.',
      sr: 'Odaberite validnu sliku.',
      es: 'Selecciona una imagen valida.',
      fr: 'Selectionnez une image valide.',
      it: 'Seleziona una immagine valida.',
    },
    uploadImageError: {
      en: 'Error uploading image.',
      de: 'Fehler beim Hochladen des Bildes.',
      bs: 'Greška pri uploadu slike.',
      hr: 'Greška pri uploadu slike.',
      sr: 'Greška pri uploadu slike.',
      es: 'Error al subir la imagen.',
      fr: 'Erreur lors de envoi de image.',
      it: 'Errore durante il caricamento.',
    },
    unsavedChangesConfirm: {
      en: 'You have unsaved changes. Are you sure you want to leave this page?',
      de: 'Sie haben ungespeicherte Aenderungen. Diese Seite verlassen?',
      bs: 'Imate nespremljene promjene. Da li ste sigurni da želite napustiti ovu stranicu?',
      hr: 'Imate nespremljene promjene. Jeste li sigurni da želite napustiti ovu stranicu?',
      sr: 'Imate nesačuvane promene. Da li ste sigurni da želite napustiti ovu stranicu?',
      es: 'Tienes cambios sin guardar. Seguro que quieres salir de esta pagina?',
      fr: 'Vous avez des modifications non enregistrees. Voulez-vous quitter cette page?',
      it: 'Hai modifiche non salvate. Vuoi lasciare questa pagina?',
    },
    search: {
      en: 'Search',
      de: 'Suchen',
      bs: 'Pretraži',
      hr: 'Pretraži',
      sr: 'Pretraži',
      es: 'Buscar',
      fr: 'Rechercher',
      it: 'Cerca',
    },
    searchUsersTitle: {
      en: 'Search users',
      de: 'Benutzer suchen',
      bs: 'Pretraga korisnika',
      hr: 'Pretraga korisnika',
      sr: 'Pretraga korisnika',
      es: 'Buscar usuarios',
      fr: 'Rechercher des utilisateurs',
      it: 'Cerca utenti',
    },
    enterNameOrUsername: {
      en: 'Enter name or username',
      de: 'Name oder Benutzername eingeben',
      bs: 'Unesite ime ili korisničko ime',
      hr: 'Unesite ime ili korisničko ime',
      sr: 'Unesite ime ili korisničko ime',
      es: 'Introduce nombre o usuario',
      fr: 'Saisir nom ou identifiant',
      it: 'Inserisci nome o utente',
    },
    searchGroupsTitle: {
      en: 'Search groups',
      de: 'Gruppen suchen',
      bs: 'Pretraga grupa',
      hr: 'Pretraga grupa',
      sr: 'Pretraga grupa',
      es: 'Buscar grupos',
      fr: 'Rechercher des groupes',
      it: 'Cerca gruppi',
    },
    enterGroupName: {
      en: 'Enter group name',
      de: 'Gruppennamen eingeben',
      bs: 'Unesite naziv grupe',
      hr: 'Unesite naziv grupe',
      sr: 'Unesite naziv grupe',
      es: 'Introduce nombre del grupo',
      fr: 'Saisir le nom du groupe',
      it: 'Inserisci nome gruppo',
    },
    viewProfile: {
      en: 'View profile',
      de: 'Profil ansehen',
      bs: 'Pogledaj profil',
      hr: 'Pogledaj profil',
      sr: 'Pogledaj profil',
      es: 'Ver perfil',
      fr: 'Voir le profil',
      it: 'Vedi profilo',
    },
    viewUserProfile: {
      en: 'View profile',
      de: 'Profil ansehen',
      bs: 'Pogledaj profil',
      hr: 'Pogledaj profil',
      sr: 'Pogledaj profil',
      es: 'Ver perfil',
      fr: 'Voir le profil',
      it: 'Vedi profilo',
    },
    addToGroup: {
      en: 'Add to group',
      de: 'Zur Gruppe hinzufuegen',
      bs: 'Dodaj u grupu',
      hr: 'Dodaj u grupu',
      sr: 'Dodaj u grupu',
      es: 'Agregar al grupo',
      fr: 'Ajouter au groupe',
      it: 'Aggiungi al gruppo',
    },
    chooseGroup: {
      en: 'Choose group',
      de: 'Gruppe auswaehlen',
      bs: 'Odaberi grupu',
      hr: 'Odaberi grupu',
      sr: 'Odaberi grupu',
      es: 'Elegir grupo',
      fr: 'Choisir un groupe',
      it: 'Scegli gruppo',
    },
    inviteUser: {
      en: 'Invite',
      de: 'Einladen',
      bs: 'Pozovi',
      hr: 'Pozovi',
      sr: 'Pozovi',
      es: 'Invitar',
      fr: 'Inviter',
      it: 'Invita',
    },
    pending: {
      en: 'Pending',
      de: 'Ausstehend',
      bs: 'Na čekanju',
      hr: 'Na čekanju',
      sr: 'Na čekanju',
      es: 'Pendiente',
      fr: 'En attente',
      it: 'In attesa',
    },
    canceling: {
      en: 'Cancelling...',
      de: 'Wird abgebrochen...',
      bs: 'Otkazivanje...',
      hr: 'Otkazivanje...',
      sr: 'Otkazivanje...',
      es: 'Cancelando...',
      fr: 'Annulation...',
      it: 'Annullamento...',
    },
    member: {
      en: 'Member',
      de: 'Mitglied',
      bs: 'Član',
      hr: 'Član',
      sr: 'Član',
      es: 'Miembro',
      fr: 'Membre',
      it: 'Membro',
    },
    sendingInvitation: {
      en: 'Sending...',
      de: 'Wird gesendet...',
      bs: 'Slanje...',
      hr: 'Slanje...',
      sr: 'Slanje...',
      es: 'Enviando...',
      fr: 'Envoi...',
      it: 'Invio...',
    },
    invitationSent: {
      en: 'Invitation sent.',
      de: 'Einladung gesendet.',
      bs: 'Pozivnica je poslana.',
      hr: 'Pozivnica je poslana.',
      sr: 'Pozivnica je poslana.',
      es: 'Invitacion enviada.',
      fr: 'Invitation envoyee.',
      it: 'Invito inviato.',
    },
    invitationCancelled: {
      en: 'Invitation cancelled.',
      de: 'Einladung abgebrochen.',
      bs: 'Pozivnica je otkazana.',
      hr: 'Pozivnica je otkazana.',
      sr: 'Pozivnica je otkazana.',
      es: 'Invitacion cancelada.',
      fr: 'Invitation annulee.',
      it: 'Invito annullato.',
    },
    cancelInvitation: {
      en: 'Cancel invitation',
      de: 'Einladung abbrechen',
      bs: 'Otkaži pozivnicu',
      hr: 'Otkaži pozivnicu',
      sr: 'Otkaži pozivnicu',
      es: 'Cancelar invitacion',
      fr: 'Annuler invitation',
      it: 'Annulla invito',
    },
    invitationSendError: {
      en: 'Error sending invitation.',
      de: 'Fehler beim Senden der Einladung.',
      bs: 'Greska pri slanju pozivnice.',
      hr: 'Greska pri slanju pozivnice.',
      sr: 'Greska pri slanju pozivnice.',
      es: 'Error al enviar la invitacion.',
      fr: 'Erreur lors de envoi de invitation.',
      it: 'Errore durante invio invito.',
    },
    cancelInvitationError: {
      en: 'Error cancelling invitation.',
      de: 'Fehler beim Abbrechen der Einladung.',
      bs: 'Greška pri otkazivanju pozivnice.',
      hr: 'Greška pri otkazivanju pozivnice.',
      sr: 'Greška pri otkazivanju pozivnice.',
      es: 'Error al cancelar la invitacion.',
      fr: 'Erreur lors de annulation de invitation.',
      it: 'Errore durante annullamento invito.',
    },
    usersLoadError: {
      en: 'Error loading users.',
      de: 'Fehler beim Laden der Benutzer.',
      bs: 'Greška pri učitavanju korisnika.',
      hr: 'Greška pri učitavanju korisnika.',
      sr: 'Greška pri učitavanju korisnika.',
      es: 'Error al cargar usuarios.',
      fr: 'Erreur lors du chargement des utilisateurs.',
      it: 'Errore durante caricamento utenti.',
    },
    userNotFound: {
      en: 'User not found.',
      de: 'Benutzer wurde nicht gefunden.',
      bs: 'Korisnik nije pronađen.',
      hr: 'Korisnik nije pronađen.',
      sr: 'Korisnik nije pronađen.',
      es: 'Usuario no encontrado.',
      fr: 'Utilisateur introuvable.',
      it: 'Utente non trovato.',
    },
    groupsLoadError: {
      en: 'Error loading groups.',
      de: 'Fehler beim Laden der Gruppen.',
      bs: 'Greška pri učitavanju grupa.',
      hr: 'Greška pri učitavanju grupa.',
      sr: 'Greška pri učitavanju grupa.',
      es: 'Error al cargar grupos.',
      fr: 'Erreur lors du chargement des groupes.',
      it: 'Errore durante caricamento gruppi.',
    },
    noUsersFound: {
      en: 'No users found',
      de: 'Keine Benutzer gefunden',
      bs: 'Nema pronađenih korisnika',
      hr: 'Nema pronađenih korisnika',
      sr: 'Nema pronađenih korisnika',
      es: 'No se encontraron usuarios',
      fr: 'Aucun utilisateur trouve',
      it: 'Nessun utente trovato',
    },
    sendMessage: {
      en: 'Send message',
      de: 'Nachricht senden',
      bs: 'Pošalji poruku',
      hr: 'Pošalji poruku',
      sr: 'Pošalji poruku',
      es: 'Enviar mensaje',
      fr: 'Envoyer un message',
      it: 'Invia messaggio',
    },
    message: {
      en: 'Message',
      de: 'Nachricht',
      bs: 'Poruka',
      hr: 'Poruka',
      sr: 'Poruka',
      es: 'Mensaje',
      fr: 'Message',
      it: 'Messaggio',
    },
    previous: {
      en: 'Previous',
      de: 'Zurueck',
      bs: 'Prethodna',
      hr: 'Prethodna',
      sr: 'Prethodna',
      es: 'Anterior',
      fr: 'Precedent',
      it: 'Precedente',
    },
    next: {
      en: 'Next',
      de: 'Weiter',
      bs: 'Sljedeća',
      hr: 'Sljedeća',
      sr: 'Sledeća',
      es: 'Siguiente',
      fr: 'Suivant',
      it: 'Successivo',
    },
    createGroup: {
      en: 'Create group',
      de: 'Gruppe erstellen',
      bs: 'Kreiraj grupu',
      hr: 'Kreiraj grupu',
      sr: 'Kreiraj grupu',
      es: 'Crear grupo',
      fr: 'Creer un groupe',
      it: 'Crea gruppo',
    },
    creating: {
      en: 'Creating...',
      de: 'Wird erstellt...',
      bs: 'Kreiranje...',
      hr: 'Kreiranje...',
      sr: 'Kreiranje...',
      es: 'Creando...',
      fr: 'Creation...',
      it: 'Creazione...',
    },
    editGroup: {
      en: 'Edit group',
      de: 'Gruppe bearbeiten',
      bs: 'Uredi grupu',
      hr: 'Uredi grupu',
      sr: 'Uredi grupu',
      es: 'Editar grupo',
      fr: 'Modifier le groupe',
      it: 'Modifica gruppo',
    },
    updateGroup: {
      en: 'Update group',
      de: 'Gruppe aktualisieren',
      bs: 'Ažuriraj grupu',
      hr: 'Ažuriraj grupu',
      sr: 'Ažuriraj grupu',
      es: 'Actualizar grupo',
      fr: 'Mettre a jour le groupe',
      it: 'Aggiorna gruppo',
    },
    updating: {
      en: 'Updating...',
      de: 'Wird aktualisiert...',
      bs: 'Ažuriranje...',
      hr: 'Ažuriranje...',
      sr: 'Ažuriranje...',
      es: 'Actualizando...',
      fr: 'Mise a jour...',
      it: 'Aggiornamento...',
    },
    groupImage: {
      en: 'Group image',
      de: 'Gruppenbild',
      bs: 'Slika grupe',
      hr: 'Slika grupe',
      sr: 'Slika grupe',
      es: 'Imagen del grupo',
      fr: 'Image du groupe',
      it: 'Immagine gruppo',
    },
    removeImage: {
      en: 'Remove image',
      de: 'Bild entfernen',
      bs: 'Ukloni sliku',
      hr: 'Ukloni sliku',
      sr: 'Ukloni sliku',
      es: 'Eliminar imagen',
      fr: 'Supprimer image',
      it: 'Rimuovi immagine',
    },
    groupName: {
      en: 'Group name',
      de: 'Gruppenname',
      bs: 'Naziv grupe',
      hr: 'Naziv grupe',
      sr: 'Naziv grupe',
      es: 'Nombre del grupo',
      fr: 'Nom du groupe',
      it: 'Nome gruppo',
    },
    groupCity: {
      en: 'City',
      de: 'Stadt',
      bs: 'Grad',
      hr: 'Grad',
      sr: 'Grad',
      es: 'Ciudad',
      fr: 'Ville',
      it: 'Citta',
    },
    sportCategory: {
      en: 'Sport category',
      de: 'Sportkategorie',
      bs: 'Kategorija sporta',
      hr: 'Kategorija sporta',
      sr: 'Kategorija sporta',
      es: 'Categoria deportiva',
      fr: 'Categorie sportive',
      it: 'Categoria sportiva',
    },
    description: {
      en: 'Description',
      de: 'Beschreibung',
      bs: 'Opis',
      hr: 'Opis',
      sr: 'Opis',
      es: 'Descripcion',
      fr: 'Description',
      it: 'Descrizione',
    },
    createGroupError: {
      en: 'An error occurred while creating the group.',
      de: 'Beim Erstellen der Gruppe ist ein Fehler aufgetreten.',
      bs: 'Došlo je do greške prilikom kreiranja grupe.',
      hr: 'Došlo je do greške prilikom kreiranja grupe.',
      sr: 'Došlo je do greške prilikom kreiranja grupe.',
      es: 'Ocurrio un error al crear el grupo.',
      fr: 'Une erreur est survenue lors de la creation du groupe.',
      it: 'Errore durante la creazione del gruppo.',
    },
    groupCreatedSuccessfully: {
      en: 'Group created successfully.',
      de: 'Gruppe erfolgreich erstellt.',
      bs: 'Grupa je uspješno kreirana.',
      hr: 'Grupa je uspješno kreirana.',
      sr: 'Grupa je uspešno kreirana.',
      es: 'Grupo creado correctamente.',
      fr: 'Groupe cree avec succes.',
      it: 'Gruppo creato con successo.',
    },
    updateGroupError: {
      en: 'An error occurred while updating the group.',
      de: 'Beim Aktualisieren der Gruppe ist ein Fehler aufgetreten.',
      bs: 'Došlo je do greške prilikom ažuriranja grupe.',
      hr: 'Došlo je do greške prilikom ažuriranja grupe.',
      sr: 'Došlo je do greške prilikom ažuriranja grupe.',
      es: 'Ocurrio un error al actualizar el grupo.',
      fr: 'Une erreur est survenue lors de la mise a jour du groupe.',
      it: 'Errore durante aggiornamento del gruppo.',
    },
    groupUpdatedSuccessfully: {
      en: 'Group updated successfully.',
      de: 'Gruppe erfolgreich aktualisiert.',
      bs: 'Grupa je uspješno ažurirana.',
      hr: 'Grupa je uspješno ažurirana.',
      sr: 'Grupa je uspešno ažurirana.',
      es: 'Grupo actualizado correctamente.',
      fr: 'Groupe mis a jour avec succes.',
      it: 'Gruppo aggiornato con successo.',
    },
    viewGroup: {
      en: 'View group',
      de: 'Gruppe ansehen',
      bs: 'Pogledaj grupu',
      hr: 'Pogledaj grupu',
      sr: 'Pogledaj grupu',
      es: 'Ver grupo',
      fr: 'Voir le groupe',
      it: 'Vedi gruppo',
    },
    deleteGroup: {
      en: 'Delete group',
      de: 'Gruppe loeschen',
      bs: 'Obriši grupu',
      hr: 'Obriši grupu',
      sr: 'Obriši grupu',
      es: 'Eliminar grupo',
      fr: 'Supprimer le groupe',
      it: 'Elimina gruppo',
    },
    confirmDeleteGroup: {
      en: 'Are you sure you want to delete this group?',
      de: 'Moechten Sie diese Gruppe wirklich loeschen?',
      bs: 'Da li ste sigurni da želite obrisati ovu grupu?',
      hr: 'Jeste li sigurni da želite obrisati ovu grupu?',
      sr: 'Da li ste sigurni da želite obrisati ovu grupu?',
      es: 'Estas seguro de que deseas eliminar este grupo?',
      fr: 'Voulez-vous vraiment supprimer ce groupe ?',
      it: 'Sei sicuro di voler eliminare questo gruppo?',
    },
    groupDeleted: {
      en: 'Group deleted successfully',
      de: 'Gruppe erfolgreich geloescht',
      bs: 'Grupa je uspješno obrisana',
      hr: 'Grupa je uspješno obrisana',
      sr: 'Grupa je uspješno obrisana',
      es: 'Grupo eliminado correctamente',
      fr: 'Le groupe a ete supprime avec succes',
      it: 'Gruppo eliminato con successo',
    },
    deleteGroupError: {
      en: 'An error occurred while deleting the group.',
      de: 'Beim Loeschen der Gruppe ist ein Fehler aufgetreten.',
      bs: 'Došlo je do greške prilikom brisanja grupe.',
      hr: 'Došlo je do greške prilikom brisanja grupe.',
      sr: 'Došlo je do greške prilikom brisanja grupe.',
      es: 'Ocurrio un error al eliminar el grupo.',
      fr: 'Une erreur est survenue lors de la suppression du groupe.',
      it: 'Si e verificato un errore durante eliminazione del gruppo.',
    },
    groupDetails: {
      en: 'Group details',
      de: 'Gruppendetails',
      bs: 'Detalji grupe',
      hr: 'Detalji grupe',
      sr: 'Detalji grupe',
      es: 'Detalles del grupo',
      fr: 'Details du groupe',
      it: 'Dettagli gruppo',
    },
    groupAdmin: {
      en: 'Group administrator',
      de: 'Gruppenadministrator',
      bs: 'Administrator grupe',
      hr: 'Administrator grupe',
      sr: 'Administrator grupe',
      es: 'Administrador del grupo',
      fr: 'Administrateur du groupe',
      it: 'Amministratore gruppo',
    },
    dateCreated: {
      en: 'Date created',
      de: 'Erstellungsdatum',
      bs: 'Datum kreiranja',
      hr: 'Datum kreiranja',
      sr: 'Datum kreiranja',
      es: 'Fecha de creacion',
      fr: 'Date de creation',
      it: 'Data creazione',
    },
    membersCountLabel: {
      en: 'Number of members',
      de: 'Anzahl der Mitglieder',
      bs: 'Broj članova',
      hr: 'Broj članova',
      sr: 'Broj članova',
      es: 'Numero de miembros',
      fr: 'Nombre de membres',
      it: 'Numero di membri',
    },
    addMembers: {
      en: 'Add members',
      de: 'Mitglieder hinzufuegen',
      bs: 'Dodaj članove',
      hr: 'Dodaj članove',
      sr: 'Dodaj članove',
      es: 'Agregar miembros',
      fr: 'Ajouter des membres',
      it: 'Aggiungi membri',
    },
    groupMembers: {
      en: 'Group members',
      de: 'Gruppenmitglieder',
      bs: 'Članovi grupe',
      hr: 'Članovi grupe',
      sr: 'Članovi grupe',
      es: 'Miembros del grupo',
      fr: 'Membres du groupe',
      it: 'Membri del gruppo',
    },
    removeFromGroup: {
      en: 'Remove from group',
      de: 'Aus Gruppe entfernen',
      bs: 'Ukloni iz grupe',
      hr: 'Ukloni iz grupe',
      sr: 'Ukloni iz grupe',
      es: 'Eliminar del grupo',
      fr: 'Retirer du groupe',
      it: 'Rimuovi dal gruppo',
    },
    confirmRemoveMember: {
      en: 'Are you sure you want to remove this member from the group?',
      de: 'Moechten Sie dieses Mitglied wirklich aus der Gruppe entfernen?',
      bs: 'Jeste li sigurni da želite ukloniti ovog člana iz grupe?',
      hr: 'Jeste li sigurni da želite ukloniti ovog člana iz grupe?',
      sr: 'Jeste li sigurni da želite ukloniti ovog člana iz grupe?',
      es: 'Seguro que quieres eliminar este miembro del grupo?',
      fr: 'Voulez-vous vraiment retirer ce membre du groupe?',
      it: 'Vuoi davvero rimuovere questo membro dal gruppo?',
    },
    memberRemovedFromGroup: {
      en: 'Member removed from group.',
      de: 'Mitglied aus der Gruppe entfernt.',
      bs: 'Član je uklonjen iz grupe.',
      hr: 'Član je uklonjen iz grupe.',
      sr: 'Član je uklonjen iz grupe.',
      es: 'Miembro eliminado del grupo.',
      fr: 'Membre retire du groupe.',
      it: 'Membro rimosso dal gruppo.',
    },
    removeMemberError: {
      en: 'Error removing member from group.',
      de: 'Fehler beim Entfernen des Mitglieds.',
      bs: 'Greška pri uklanjanju člana iz grupe.',
      hr: 'Greška pri uklanjanju člana iz grupe.',
      sr: 'Greška pri uklanjanju člana iz grupe.',
      es: 'Error al eliminar miembro del grupo.',
      fr: 'Erreur lors du retrait du membre.',
      it: 'Errore durante la rimozione del membro.',
    },
    memberOfGroup: {
      en: 'You are a member of this group',
      de: 'Sie sind Mitglied dieser Gruppe',
      bs: 'Član ste ove grupe',
      hr: 'Član ste ove grupe',
      sr: 'Član ste ove grupe',
      es: 'Eres miembro de este grupo',
      fr: 'Vous etes membre de ce groupe',
      it: 'Sei membro di questo gruppo',
    },
    leaveGroup: {
      en: 'Leave group',
      de: 'Gruppe verlassen',
      bs: 'Napusti grupu',
      hr: 'Napusti grupu',
      sr: 'Napusti grupu',
      es: 'Salir del grupo',
      fr: 'Quitter le groupe',
      it: 'Lascia il gruppo',
    },
    confirmLeaveGroup: {
      en: 'Are you sure you want to leave this group?',
      de: 'Moechten Sie diese Gruppe wirklich verlassen?',
      bs: 'Jeste li sigurni da želite napustiti ovu grupu?',
      hr: 'Jeste li sigurni da želite napustiti ovu grupu?',
      sr: 'Jeste li sigurni da želite napustiti ovu grupu?',
      es: 'Seguro que quieres salir de este grupo?',
      fr: 'Voulez-vous vraiment quitter ce groupe?',
      it: 'Vuoi davvero lasciare questo gruppo?',
    },
    leftGroup: {
      en: 'You left the group.',
      de: 'Sie haben die Gruppe verlassen.',
      bs: 'Napustili ste grupu.',
      hr: 'Napustili ste grupu.',
      sr: 'Napustili ste grupu.',
      es: 'Has salido del grupo.',
      fr: 'Vous avez quitte le groupe.',
      it: 'Hai lasciato il gruppo.',
    },
    leaveGroupError: {
      en: 'Error leaving group.',
      de: 'Fehler beim Verlassen der Gruppe.',
      bs: 'Greška pri napuštanju grupe.',
      hr: 'Greška pri napuštanju grupe.',
      sr: 'Greška pri napuštanju grupe.',
      es: 'Error al salir del grupo.',
      fr: 'Erreur lors de la sortie du groupe.',
      it: 'Errore durante uscita dal gruppo.',
    },
    requestAccess: {
      en: 'Request access',
      de: 'Zugang anfragen',
      bs: 'Zatraži pristup',
      hr: 'Zatraži pristup',
      sr: 'Zatraži pristup',
      es: 'Solicitar acceso',
      fr: 'Demander acces',
      it: 'Richiedi accesso',
    },
    requestingAccess: {
      en: 'Requesting...',
      de: 'Wird angefragt...',
      bs: 'Slanje zahtjeva...',
      hr: 'Slanje zahtjeva...',
      sr: 'Slanje zahtjeva...',
      es: 'Solicitando...',
      fr: 'Demande en cours...',
      it: 'Richiesta...',
    },
    accessRequested: {
      en: 'Access requested',
      de: 'Zugang angefragt',
      bs: 'Zahtjev poslan',
      hr: 'Zahtjev poslan',
      sr: 'Zahtjev poslan',
      es: 'Solicitud enviada',
      fr: 'Demande envoyee',
      it: 'Richiesta inviata',
    },
    cancelJoinRequest: {
      en: 'Cancel join request',
      de: 'Beitrittsanfrage abbrechen',
      bs: 'Otkaži zahtjev',
      hr: 'Otkaži zahtjev',
      sr: 'Otkaži zahtjev',
      es: 'Cancelar solicitud',
      fr: 'Annuler la demande',
      it: 'Annulla richiesta',
    },
    joinRequestCancelled: {
      en: 'Join request cancelled.',
      de: 'Beitrittsanfrage abgebrochen.',
      bs: 'Zahtjev je otkazan.',
      hr: 'Zahtjev je otkazan.',
      sr: 'Zahtjev je otkazan.',
      es: 'Solicitud cancelada.',
      fr: 'Demande annulee.',
      it: 'Richiesta annullata.',
    },
    requestAccessError: {
      en: 'Error sending access request.',
      de: 'Fehler beim Senden der Zugangsanfrage.',
      bs: 'Greška pri slanju zahtjeva za pristup.',
      hr: 'Greška pri slanju zahtjeva za pristup.',
      sr: 'Greška pri slanju zahtjeva za pristup.',
      es: 'Error al enviar la solicitud.',
      fr: 'Erreur lors de envoi de la demande.',
      it: 'Errore durante invio richiesta.',
    },
    cancelJoinRequestError: {
      en: 'Error cancelling join request.',
      de: 'Fehler beim Abbrechen der Beitrittsanfrage.',
      bs: 'Greška pri otkazivanju zahtjeva.',
      hr: 'Greška pri otkazivanju zahtjeva.',
      sr: 'Greška pri otkazivanju zahtjeva.',
      es: 'Error al cancelar la solicitud.',
      fr: 'Erreur lors de annulation de la demande.',
      it: 'Errore durante annullamento richiesta.',
    },
    backToGroups: {
      en: 'Back to groups',
      de: 'Zurueck zu Gruppen',
      bs: 'Nazad na grupe',
      hr: 'Nazad na grupe',
      sr: 'Nazad na grupe',
      es: 'Volver a grupos',
      fr: 'Retour aux groupes',
      it: 'Torna ai gruppi',
    },
    backToUsers: {
      en: 'Back to users',
      de: 'Zurueck zu Benutzern',
      bs: 'Nazad na korisnike',
      hr: 'Nazad na korisnike',
      sr: 'Nazad na korisnike',
      es: 'Volver a usuarios',
      fr: 'Retour aux utilisateurs',
      it: 'Torna agli utenti',
    },
    groupDetailsLoadError: {
      en: 'Error loading group details.',
      de: 'Fehler beim Laden der Gruppendetails.',
      bs: 'Greška pri učitavanju detalja grupe.',
      hr: 'Greška pri učitavanju detalja grupe.',
      sr: 'Greška pri učitavanju detalja grupe.',
      es: 'Error al cargar detalles del grupo.',
      fr: 'Erreur lors du chargement du groupe.',
      it: 'Errore durante caricamento dettagli.',
    },
    requestJoinGroup: {
      en: 'Send request to join group',
      de: 'Anfrage zum Beitritt senden',
      bs: 'Pošalji zahtjev za pridruživanje grupi',
      hr: 'Pošalji zahtjev za pridruživanje grupi',
      sr: 'Pošalji zahtev za pridruživanje grupi',
      es: 'Enviar solicitud para unirse al grupo',
      fr: 'Envoyer une demande pour rejoindre le groupe',
      it: 'Invia richiesta di adesione',
    },
    myGroups: {
      en: 'My groups',
      de: 'Meine Gruppen',
      bs: 'Moje grupe',
      hr: 'Moje grupe',
      sr: 'Moje grupe',
      es: 'Mis grupos',
      fr: 'Mes groupes',
      it: 'I miei gruppi',
    },
    memberships: {
      en: 'Memberships',
      de: 'Mitgliedschaften',
      bs: 'Članstva',
      hr: 'Članstva',
      sr: 'Članstva',
      es: 'Membresias',
      fr: 'Adhesions',
      it: 'Iscrizioni',
    },
    members: {
      en: 'members',
      de: 'Mitglieder',
      bs: 'članova',
      hr: 'članova',
      sr: 'članova',
      es: 'miembros',
      fr: 'membres',
      it: 'membri',
    },
    noMembers: {
      en: 'No members',
      de: 'Keine Mitglieder',
      bs: 'Nema članova',
      hr: 'Nema članova',
      sr: 'Nema članova',
      es: 'Sin miembros',
      fr: 'Aucun membre',
      it: 'Nessun membro',
    },
    noAdminGroups: {
      en: 'You have not created any groups',
      de: 'Sie haben keine Gruppen erstellt',
      bs: 'Nemate napravljenih grupa',
      hr: 'Nemate napravljenih grupa',
      sr: 'Nemate napravljenih grupa',
      es: 'No has creado grupos',
      fr: 'Vous navez cree aucun groupe',
      it: 'Non hai creato gruppi',
    },
    noMemberGroups: {
      en: 'You are not a member of any group',
      de: 'Sie sind in keiner Gruppe Mitglied',
      bs: 'Niste član nijedne grupe',
      hr: 'Niste član nijedne grupe',
      sr: 'Niste član nijedne grupe',
      es: 'No eres miembro de ningun grupo',
      fr: 'Vous netes membre daucun groupe',
      it: 'Non sei membro di alcun gruppo',
    },
    noGroupsFound: {
      en: 'No groups found',
      de: 'Keine Gruppen gefunden',
      bs: 'Nema pronađenih grupa',
      hr: 'Nema pronađenih grupa',
      sr: 'Nema pronađenih grupa',
      es: 'No se encontraron grupos',
      fr: 'Aucun groupe trouve',
      it: 'Nessun gruppo trovato',
    },
    findUsers: {
      en: 'Find people to play sports with',
      de: 'Finden Sie Leute fuer Sporttermine',
      bs: 'Pronađite ljude za sportske termine',
      hr: 'Pronađite ljude za sportske termine',
      sr: 'Pronađite ljude za sportske termine',
      es: 'Encuentra personas para hacer deporte',
      fr: 'Trouvez des personnes pour faire du sport',
      it: 'Trova persone per fare sport',
    },
    searchUsers: {
      en: 'Search users',
      de: 'Benutzer suchen',
      bs: 'Pretraži korisnike',
      hr: 'Pretraži korisnike',
      sr: 'Pretraži korisnike',
      es: 'Buscar usuarios',
      fr: 'Rechercher des utilisateurs',
      it: 'Cerca utenti',
    },
    toggleNavigation: {
      en: 'Toggle navigation',
      de: 'Navigation umschalten',
      bs: 'Otvori ili zatvori navigaciju',
      hr: 'Otvori ili zatvori navigaciju',
      sr: 'Otvori ili zatvori navigaciju',
      es: 'Alternar navegacion',
      fr: 'Basculer la navigation',
      it: 'Attiva navigazione',
    },
    loading: {
      en: 'Loading...',
      de: 'Laden...',
      bs: 'Učitavanje...',
      hr: 'Učitavanje...',
      sr: 'Učitavanje...',
      es: 'Cargando...',
      fr: 'Chargement...',
      it: 'Caricamento...',
    },
    send: {
      en: 'Send',
      de: 'Senden',
      bs: 'Pošalji',
      hr: 'Pošalji',
      sr: 'Pošalji',
      es: 'Enviar',
      fr: 'Envoyer',
      it: 'Invia',
    },
    sending: {
      en: 'Sending...',
      de: 'Wird gesendet...',
      bs: 'Slanje...',
      hr: 'Slanje...',
      sr: 'Slanje...',
      es: 'Enviando...',
      fr: 'Envoi...',
      it: 'Invio...',
    },
    writeMessage: {
      en: 'Write a message',
      de: 'Nachricht schreiben',
      bs: 'Napišite poruku',
      hr: 'Napišite poruku',
      sr: 'Napišite poruku',
      es: 'Escribe un mensaje',
      fr: 'Ecrivez un message',
      it: 'Scrivi un messaggio',
    },
    backToGroupDetails: {
      en: 'Back to group details',
      de: 'Zurueck zu Gruppendetails',
      bs: 'Nazad na detalje grupe',
      hr: 'Nazad na detalje grupe',
      sr: 'Nazad na detalje grupe',
      es: 'Volver a detalles del grupo',
      fr: 'Retour aux details du groupe',
      it: 'Torna ai dettagli del gruppo',
    },
    groupChat: {
      en: 'Chat',
      de: 'Chat',
      bs: 'Dopisivanje',
      hr: 'Dopisivanje',
      sr: 'Dopisivanje',
      es: 'Chat',
      fr: 'Discussion',
      it: 'Chat',
    },
    noGroupMessages: {
      en: 'No messages yet',
      de: 'Noch keine Nachrichten',
      bs: 'Još nema poruka',
      hr: 'Još nema poruka',
      sr: 'Još nema poruka',
      es: 'Aun no hay mensajes',
      fr: 'Pas encore de messages',
      it: 'Ancora nessun messaggio',
    },
    groupChatLoadError: {
      en: 'Error loading group chat.',
      de: 'Fehler beim Laden des Gruppenchats.',
      bs: 'Greška pri učitavanju grupnog chata.',
      hr: 'Greška pri učitavanju grupnog chata.',
      sr: 'Greška pri učitavanju grupnog chata.',
      es: 'Error al cargar el chat grupal.',
      fr: 'Erreur lors du chargement du chat de groupe.',
      it: 'Errore durante caricamento chat di gruppo.',
    },
    groupChatSendError: {
      en: 'Error sending message.',
      de: 'Fehler beim Senden der Nachricht.',
      bs: 'Greška pri slanju poruke.',
      hr: 'Greška pri slanju poruke.',
      sr: 'Greška pri slanju poruke.',
      es: 'Error al enviar mensaje.',
      fr: 'Erreur lors de envoi du message.',
      it: 'Errore durante invio del messaggio.',
    },
    messages: {
      en: 'Messages',
      de: 'Nachrichten',
      bs: 'Poruke',
      hr: 'Poruke',
      sr: 'Poruke',
      es: 'Mensajes',
      fr: 'Messages',
      it: 'Messaggi',
    },
    noMessageNotifications: {
      en: 'No recent messages',
      de: 'Keine neuen Nachrichten',
      bs: 'Nema novih poruka',
      hr: 'Nema novih poruka',
      sr: 'Nema novih poruka',
      es: 'No hay mensajes novih',
      fr: 'Aucun message recent',
      it: 'Nessun messaggio recente',
    },
    noChats: {
      en: 'No chats',
      de: 'Keine Chats',
      bs: 'Nema poruka',
      hr: 'Nema poruka',
      sr: 'Nema poruka',
      es: 'No hay chats',
      fr: 'Aucun chat',
      it: 'Nessuna chat',
    },
    activeNow: {
      en: 'Active now',
      de: 'Jetzt aktiv',
      bs: 'Aktivan sada',
      hr: 'Aktivan sada',
      sr: 'Aktivan sada',
      es: 'Activo ahora',
      fr: 'Actif maintenant',
      it: 'Attivo ora',
    },
    offline: {
      en: 'Offline',
      de: 'Offline',
      bs: 'Offline',
      hr: 'Offline',
      sr: 'Offline',
      es: 'Desconectado',
      fr: 'Hors ligne',
      it: 'Offline',
    },
    activeMembers: {
      en: 'Active members',
      de: 'Aktive Mitglieder',
      bs: 'Aktivni članovi',
      hr: 'Aktivni članovi',
      sr: 'Aktivni članovi',
      es: 'Miembros activos',
      fr: 'Membres actifs',
      it: 'Membri attivi',
    },
    noActiveMembers: {
      en: 'No active members',
      de: 'Keine aktiven Mitglieder',
      bs: 'Nema aktivnih članova',
      hr: 'Nema aktivnih članova',
      sr: 'Nema aktivnih članova',
      es: 'No hay miembros activos',
      fr: 'Aucun membre actif',
      it: 'Nessun membro attivo',
    },
    noPrivateMessages: {
      en: 'No messages yet',
      de: 'Noch keine Nachrichten',
      bs: 'Još nema poruka',
      hr: 'Još nema poruka',
      sr: 'Još nema poruka',
      es: 'Aun no hay mensajes',
      fr: 'Pas encore de messages',
      it: 'Ancora nessun messaggio',
    },
    privateChatLoadError: {
      en: 'Error loading private chat.',
      de: 'Fehler beim Laden des privaten Chats.',
      bs: 'Greška pri učitavanju privatnog chata.',
      hr: 'Greška pri učitavanju privatnog chata.',
      sr: 'Greška pri učitavanju privatnog chata.',
      es: 'Error al cargar chat privado.',
      fr: 'Erreur lors du chargement du chat prive.',
      it: 'Errore durante caricamento chat privato.',
    },
    privateChatSendError: {
      en: 'Error sending private message.',
      de: 'Fehler beim Senden der privaten Nachricht.',
      bs: 'Greška pri slanju privatne poruke.',
      hr: 'Greška pri slanju privatne poruke.',
      sr: 'Greška pri slanju privatne poruke.',
      es: 'Error al enviar mensaje privado.',
      fr: 'Erreur lors de envoi du message prive.',
      it: 'Errore durante invio del messaggio privato.',
    },
    sent: {
      en: 'Sent',
      de: 'Gesendet',
      bs: 'Poslano',
      hr: 'Poslano',
      sr: 'Poslato',
      es: 'Enviado',
      fr: 'Envoye',
      it: 'Inviato',
    },
    delivered: {
      en: 'Delivered',
      de: 'Zugestellt',
      bs: 'Dostavljeno',
      hr: 'Dostavljeno',
      sr: 'Dostavljeno',
      es: 'Entregado',
      fr: 'Livre',
      it: 'Consegnato',
    },
    seen: {
      en: 'Seen',
      de: 'Gesehen',
      bs: 'Pročitano',
      hr: 'Pročitano',
      sr: 'Pročitano',
      es: 'Visto',
      fr: 'Vu',
      it: 'Visto',
    },
    seenBy: {
      en: 'Seen by',
      de: 'Gesehen von',
      bs: 'Pročitali',
      hr: 'Pročitali',
      sr: 'Pročitali',
      es: 'Visto por',
      fr: 'Vu par',
      it: 'Visto da',
    },
    typing: {
      en: 'Typing...',
      de: 'Schreibt...',
      bs: 'Piše...',
      hr: 'Piše...',
      sr: 'Piše...',
      es: 'Escribiendo...',
      fr: 'Ecrit...',
      it: 'Sta scrivendo...',
    },
    isTyping: {
      en: 'is typing...',
      de: 'schreibt...',
      bs: 'piše...',
      hr: 'piše...',
      sr: 'piše...',
      es: 'esta escribiendo...',
      fr: 'ecrit...',
      it: 'sta scrivendo...',
    },
    usersAreTyping: {
      en: '{count} users are typing...',
      de: '{count} Benutzer schreiben...',
      bs: '{count} korisnika pišu...',
      hr: '{count} korisnika pišu...',
      sr: '{count} korisnika pišu...',
      es: '{count} usuarios estan escribiendo...',
      fr: '{count} utilisateurs ecrivent...',
      it: '{count} utenti stanno scrivendo...',
    },
    searchUsersSubtitle: {
      en: 'Find people on the platform and play sports together',
      de: 'Finden Sie Leute auf der Plattform und treiben Sie gemeinsam Sport',
      bs: 'Pronadite ljude na platformi i igrajte sport zajedno',
      hr: 'Pronadite ljude na platformi i igrajte sport zajedno',
      sr: 'Pronadite ljude na platformi i igrajte sport zajedno',
      es: 'Encuentra personas en la plataforma y practiquen deporte juntos',
      fr: 'Trouvez des personnes sur la plateforme et faites du sport ensemble',
      it: 'Trova persone sulla piattaforma e fate sport insieme',
    },
    searchGroupsSubtitle: {
      en: 'Browse your groups and jump back into the communities you follow',
      de: 'Durchsuchen Sie Ihre Gruppen und kehren Sie zu Ihren Communities zurueck',
      bs: 'Pregledajte svoje grupe i brzo se vratite u zajednice koje pratite',
      hr: 'Pregledajte svoje grupe i brzo se vratite u zajednice koje pratite',
      sr: 'Pregledajte svoje grupe i brzo se vratite u zajednice koje pratite',
      es: 'Explora tus grupos y vuelve a las comunidades que sigues',
      fr: 'Parcourez vos groupes et revenez dans les communautes que vous suivez',
      it: 'Sfoglia i tuoi gruppi e torna nelle comunita che segui',
    },
    filter: {
      en: 'Filter',
      de: 'Filter',
      bs: 'Filter',
      hr: 'Filter',
      sr: 'Filter',
      es: 'Filtro',
      fr: 'Filtre',
      it: 'Filtro',
    },
    sortBy: {
      en: 'Sort by',
      de: 'Sortieren nach',
      bs: 'Sortiraj po',
      hr: 'Sortiraj po',
      sr: 'Sortiraj po',
      es: 'Ordenar por',
      fr: 'Trier par',
      it: 'Ordina per',
    },
    alphabetical: {
      en: 'Alphabetical',
      de: 'Alphabetisch',
      bs: 'Abecedno',
      hr: 'Abecedno',
      sr: 'Abecedno',
      es: 'Alfabetico',
      fr: 'Alphabetique',
      it: 'Alfabetico',
    },
    alphabeticalAsc: {
      en: 'A to Z',
      de: 'A bis Z',
      bs: 'Od A do Z',
      hr: 'Od A do Z',
      sr: 'Od A do Z',
      es: 'De A a Z',
      fr: 'De A a Z',
      it: 'Da A a Z',
    },
    alphabeticalDesc: {
      en: 'Z to A',
      de: 'Z bis A',
      bs: 'Od Z do A',
      hr: 'Od Z do A',
      sr: 'Od Z do A',
      es: 'De Z a A',
      fr: 'De Z a A',
      it: 'Da Z a A',
    },
    admin: {
      en: 'Admin',
      de: 'Admin',
      bs: 'Admin',
      hr: 'Admin',
      sr: 'Admin',
      es: 'Admin',
      fr: 'Admin',
      it: 'Admin',
    },
    membership: {
      en: 'Membership',
      de: 'Mitgliedschaft',
      bs: 'Članstvo',
      hr: 'Clanstvo',
      sr: 'Clanstvo',
      es: 'Membresia',
      fr: 'Adhesion',
      it: 'Iscrizione',
    },
    allGroups: {
      en: 'All groups',
      de: 'Alle Gruppen',
      bs: 'Sve grupe',
      hr: 'Sve grupe',
      sr: 'Sve grupe',
      es: 'Todos los grupos',
      fr: 'Tous les groupes',
      it: 'Tutti i gruppi',
    },
    allUsers: {
      en: 'All users',
      de: 'Alle Benutzer',
      bs: 'Svi korisnici',
      hr: 'Svi korisnici',
      sr: 'Svi korisnici',
      es: 'Todos los usuarios',
      fr: 'Tous les utilisateurs',
      it: 'Tutti gli utenti',
    },
    commonGroups: {
      en: 'Common groups',
      de: 'Gemeinsame Gruppen',
      bs: 'Zajednicke grupe',
      hr: 'Zajednicke grupe',
      sr: 'Zajednicke grupe',
      es: 'Grupos en comun',
      fr: 'Groupes en commun',
      it: 'Gruppi in comune',
    },
    usersFound: {
      en: 'users found',
      de: 'Benutzer gefunden',
      bs: 'korisnika pronadjeno',
      hr: 'korisnika pronadjeno',
      sr: 'korisnika pronadjeno',
      es: 'usuarios encontrados',
      fr: 'utilisateurs trouves',
      it: 'utenti trovati',
    },
    groupsFound: {
      en: 'groups found',
      de: 'Gruppen gefunden',
      bs: 'grupa pronadjeno',
      hr: 'grupa pronadjeno',
      sr: 'grupa pronadjeno',
      es: 'grupos encontrados',
      fr: 'groupes trouves',
      it: 'gruppi trovati',
    },
  };

  get currentLanguage(): LanguageCode {
    return this.languageSubject.value;
  }

  setLanguage(language: string): void {
    const languageCode = this.isSupportedLanguage(language)
      ? language
      : this.defaultLanguage;

    localStorage.setItem('appLanguage', languageCode);
    document.documentElement.lang = languageCode;
    this.languageSubject.next(languageCode);
  }

  translate(key: string): string {
    return (
      this.translations[key]?.[this.currentLanguage] ||
      this.translations[key]?.[this.defaultLanguage] ||
      key
    );
  }

  getLanguageName(code: string): string {
    return (
      this.languages.find((language) => language.code === code)?.name ||
      this.languages.find((language) => language.code === this.defaultLanguage)!.name
    );
  }

  private getSavedLanguage(): LanguageCode {
    const savedLanguage = localStorage.getItem('appLanguage');
    return this.isSupportedLanguage(savedLanguage)
      ? savedLanguage
      : this.defaultLanguage;
  }

  private isSupportedLanguage(language: string | null): language is LanguageCode {
    return ['en', 'de', 'bs', 'hr', 'sr', 'es', 'fr', 'it'].includes(
      language || '',
    );
  }
}
