import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

type LanguageCode = 'en' | 'de' | 'bs' | 'hr' | 'sr' | 'es' | 'fr' | 'it';
type TranslationDictionary = Record<string, Record<LanguageCode, string>>;

@Injectable({
  providedIn: 'root',
})
export class LanguageService {
  readonly languages = [
    { code: 'en', name: 'English' },
    { code: 'de', name: 'Deutsch' },
    { code: 'bs', name: 'Bosanski' },
    { code: 'hr', name: 'Hrvatski' },
    { code: 'sr', name: 'Srpski' },
    { code: 'es', name: 'Espanol' },
    { code: 'fr', name: 'Francais' },
    { code: 'it', name: 'Italiano' },
  ];

  private readonly defaultLanguage: LanguageCode = 'bs';
  private readonly languageSubject = new BehaviorSubject<LanguageCode>(
    this.getSavedLanguage(),
  );

  readonly language$ = this.languageSubject.asObservable();

  private readonly translations: TranslationDictionary = {
    appTitle: {
      en: 'Sports booking',
      de: 'Sporttermin-Reservierung',
      bs: 'Rezervacija sportskih termina',
      hr: 'Rezervacija sportskih termina',
      sr: 'Rezervacija sportskih termina',
      es: 'Reserva de pistas deportivas',
      fr: 'Reservation de terrains sportifs',
      it: 'Prenotazione campi sportivi',
    },
    home: {
      en: 'Home',
      de: 'Startseite',
      bs: 'Početna',
      hr: 'Početna',
      sr: 'Početna',
      es: 'Inicio',
      fr: 'Accueil',
      it: 'Home',
    },
    sportsFields: {
      en: 'Sports fields',
      de: 'Sportplaetze',
      bs: 'Sportski tereni',
      hr: 'Sportski tereni',
      sr: 'Sportski tereni',
      es: 'Campos deportivos',
      fr: 'Terrains sportifs',
      it: 'Campi sportivi',
    },
    users: {
      en: 'Users',
      de: 'Benutzer',
      bs: 'Korisnici',
      hr: 'Korisnici',
      sr: 'Korisnici',
      es: 'Usuarios',
      fr: 'Utilisateurs',
      it: 'Utenti',
    },
    groups: {
      en: 'Groups',
      de: 'Gruppen',
      bs: 'Grupe',
      hr: 'Grupe',
      sr: 'Grupe',
      es: 'Grupos',
      fr: 'Groupes',
      it: 'Gruppi',
    },
    welcome: {
      en: 'Welcome',
      de: 'Willkommen',
      bs: 'Dobrodošli',
      hr: 'Dobrodošli',
      sr: 'Dobrodošli',
      es: 'Bienvenido',
      fr: 'Bienvenue',
      it: 'Benvenuto',
    },
    profile: {
      en: 'Profile',
      de: 'Profil',
      bs: 'Profil',
      hr: 'Profil',
      sr: 'Profil',
      es: 'Perfil',
      fr: 'Profil',
      it: 'Profilo',
    },
    settings: {
      en: 'Settings',
      de: 'Einstellungen',
      bs: 'Postavke',
      hr: 'Postavke',
      sr: 'Podešavanja',
      es: 'Configuracion',
      fr: 'Parametres',
      it: 'Impostazioni',
    },
    logout: {
      en: 'Logout',
      de: 'Abmelden',
      bs: 'Odjava',
      hr: 'Odjava',
      sr: 'Odjava',
      es: 'Cerrar sesion',
      fr: 'Deconnexion',
      it: 'Esci',
    },
    login: {
      en: 'Login',
      de: 'Anmelden',
      bs: 'Prijava',
      hr: 'Prijava',
      sr: 'Prijava',
      es: 'Iniciar sesion',
      fr: 'Connexion',
      it: 'Accesso',
    },
    register: {
      en: 'Register',
      de: 'Registrieren',
      bs: 'Registracija',
      hr: 'Registracija',
      sr: 'Registracija',
      es: 'Registro',
      fr: 'Inscription',
      it: 'Registrazione',
    },
    username: {
      en: 'Username',
      de: 'Benutzername',
      bs: 'Korisničko ime',
      hr: 'Korisničko ime',
      sr: 'Korisničko ime',
      es: 'Nombre de usuario',
      fr: 'Nom utilisateur',
      it: 'Nome utente',
    },
    password: {
      en: 'Password',
      de: 'Passwort',
      bs: 'Lozinka',
      hr: 'Lozinka',
      sr: 'Lozinka',
      es: 'Contrasena',
      fr: 'Mot de passe',
      it: 'Password',
    },
    fullName: {
      en: 'Full name',
      de: 'Vor- und Nachname',
      bs: 'Ime i prezime',
      hr: 'Ime i prezime',
      sr: 'Ime i prezime',
      es: 'Nombre completo',
      fr: 'Nom complet',
      it: 'Nome completo',
    },
    email: {
      en: 'Email',
      de: 'E-Mail',
      bs: 'Email',
      hr: 'Email',
      sr: 'Email',
      es: 'Email',
      fr: 'Email',
      it: 'Email',
    },
    phone: {
      en: 'Phone',
      de: 'Telefon',
      bs: 'Telefon',
      hr: 'Telefon',
      sr: 'Telefon',
      es: 'Telefono',
      fr: 'Telephone',
      it: 'Telefono',
    },
    phoneNumber: {
      en: 'Phone number',
      de: 'Telefonnummer',
      bs: 'Broj telefona',
      hr: 'Broj telefona',
      sr: 'Broj telefona',
      es: 'Numero de telefono',
      fr: 'Numero de telephone',
      it: 'Numero di telefono',
    },
    requiredField: {
      en: 'This field is required',
      de: 'Dieses Feld ist erforderlich',
      bs: 'Ovo polje je obavezno',
      hr: 'Ovo polje je obavezno',
      sr: 'Ovo polje je obavezno',
      es: 'Este campo es obligatorio',
      fr: 'Ce champ est obligatoire',
      it: 'Questo campo e obbligatorio',
    },
    invalidEmail: {
      en: 'Invalid email',
      de: 'Ungueltige E-Mail',
      bs: 'Nevalidan e-mail',
      hr: 'Neispravan e-mail',
      sr: 'Nevalidan e-mail',
      es: 'Email invalido',
      fr: 'Email invalide',
      it: 'Email non valida',
    },
    invalidPhone: {
      en: 'Invalid phone number',
      de: 'Ungueltige Telefonnummer',
      bs: 'Nevalidan broj telefona',
      hr: 'Neispravan broj telefona',
      sr: 'Nevalidan broj telefona',
      es: 'Telefono invalido',
      fr: 'Telephone invalide',
      it: 'Telefono non valido',
    },
    emailTaken: {
      en: 'Email is already in use',
      de: 'E-Mail wird bereits verwendet',
      bs: 'E-mail je već u upotrebi',
      hr: 'E-mail je već u upotrebi',
      sr: 'E-mail je već u upotrebi',
      es: 'El email ya esta en uso',
      fr: 'Email deja utilise',
      it: 'Email gia in uso',
    },
    phoneTaken: {
      en: 'Phone number is already in use',
      de: 'Telefonnummer wird bereits verwendet',
      bs: 'Broj telefona je već u upotrebi',
      hr: 'Broj telefona je već u upotrebi',
      sr: 'Broj telefona je već u upotrebi',
      es: 'El telefono ya esta en uso',
      fr: 'Telephone deja utilise',
      it: 'Telefono gia in uso',
    },
    usernameTaken: {
      en: 'Username is already in use',
      de: 'Benutzername wird bereits verwendet',
      bs: 'Korisničko ime je već u upotrebi',
      hr: 'Korisničko ime je već u upotrebi',
      sr: 'Korisničko ime je već u upotrebi',
      es: 'El usuario ya esta en uso',
      fr: 'Nom utilisateur deja utilise',
      it: 'Nome utente gia in uso',
    },
    invalidLogin: {
      en: 'Invalid username or password',
      de: 'Ungueltiger Benutzername oder Passwort',
      bs: 'Nevalidno korisničko ime ili lozinka',
      hr: 'Neispravno korisničko ime ili lozinka',
      sr: 'Nevalidno korisničko ime ili lozinka',
      es: 'Usuario o contrasena invalidos',
      fr: 'Identifiant ou mot de passe invalide',
      it: 'Nome utente o password non validi',
    },
    noProfile: {
      en: "Don't have a profile?",
      de: 'Noch kein Profil?',
      bs: 'Nemate profil?',
      hr: 'Nemate profil?',
      sr: 'Nemate profil?',
      es: 'No tienes perfil?',
      fr: 'Vous navez pas de profil?',
      it: 'Non hai un profilo?',
    },
    haveProfile: {
      en: 'Already have a profile?',
      de: 'Haben Sie bereits ein Profil?',
      bs: 'Već imate profil?',
      hr: 'Već imate profil?',
      sr: 'Već imate profil?',
      es: 'Ya tienes perfil?',
      fr: 'Vous avez deja un profil?',
      it: 'Hai gia un profilo?',
    },
    notifications: {
      en: 'Notifications',
      de: 'Benachrichtigungen',
      bs: 'Obavijesti',
      hr: 'Obavijesti',
      sr: 'Obaveštenja',
      es: 'Notificaciones',
      fr: 'Notifications',
      it: 'Notifiche',
    },
    receiveEmailNotifications: {
      en: 'Receive email notifications',
      de: 'E-Mail-Benachrichtigungen erhalten',
      bs: 'Primaj email obavijesti',
      hr: 'Primaj email obavijesti',
      sr: 'Primaj email obaveštenja',
      es: 'Recibir notificaciones por email',
      fr: 'Recevoir des notifications par email',
      it: 'Ricevi notifiche email',
    },
    appearance: {
      en: 'Appearance',
      de: 'Darstellung',
      bs: 'Izgled',
      hr: 'Izgled',
      sr: 'Izgled',
      es: 'Apariencia',
      fr: 'Apparence',
      it: 'Aspetto',
    },
    darkMode: {
      en: 'Dark mode',
      de: 'Dunkler Modus',
      bs: 'Tamni mod',
      hr: 'Tamni mod',
      sr: 'Tamni režim',
      es: 'Modo oscuro',
      fr: 'Mode sombre',
      it: 'Modalita scura',
    },
    appLanguage: {
      en: 'App language',
      de: 'App-Sprache',
      bs: 'Jezik aplikacije',
      hr: 'Jezik aplikacije',
      sr: 'Jezik aplikacije',
      es: 'Idioma de la aplicacion',
      fr: 'Langue de application',
      it: 'Lingua app',
    },
    selectedLanguage: {
      en: 'Selected language',
      de: 'Ausgewaehlte Sprache',
      bs: 'Odabrani jezik',
      hr: 'Odabrani jezik',
      sr: 'Odabrani jezik',
      es: 'Idioma seleccionado',
      fr: 'Langue selectionnee',
      it: 'Lingua selezionata',
    },
    currentLanguage: {
      en: 'Current language',
      de: 'Aktuelle Sprache',
      bs: 'Trenutno odabrani jezik',
      hr: 'Trenutno odabrani jezik',
      sr: 'Trenutno odabrani jezik',
      es: 'Idioma actual',
      fr: 'Langue actuelle',
      it: 'Lingua attuale',
    },
    languageSaved: {
      en: 'App language saved.',
      de: 'App-Sprache gespeichert.',
      bs: 'Jezik aplikacije je sačuvan.',
      hr: 'Jezik aplikacije je spremljen.',
      sr: 'Jezik aplikacije je sačuvan.',
      es: 'Idioma guardado.',
      fr: 'Langue enregistree.',
      it: 'Lingua salvata.',
    },
    account: {
      en: 'Account',
      de: 'Konto',
      bs: 'Račun',
      hr: 'Račun',
      sr: 'Nalog',
      es: 'Cuenta',
      fr: 'Compte',
      it: 'Account',
    },
    accountInfo: {
      en: 'Account information',
      de: 'Kontoinformationen',
      bs: 'Informacije o računu',
      hr: 'Informacije o računu',
      sr: 'Informacije o nalogu',
      es: 'Informacion de la cuenta',
      fr: 'Informations du compte',
      it: 'Informazioni account',
    },
    changeUsername: {
      en: 'Change username',
      de: 'Benutzername aendern',
      bs: 'Promijeni korisničko ime',
      hr: 'Promijeni korisničko ime',
      sr: 'Promeni korisničko ime',
      es: 'Cambiar usuario',
      fr: 'Changer le nom utilisateur',
      it: 'Cambia nome utente',
    },
    logoutAllDevices: {
      en: 'Logout from all devices',
      de: 'Von allen Geraeten abmelden',
      bs: 'Odjavi sa svih uređaja',
      hr: 'Odjavi sa svih uređaja',
      sr: 'Odjavi se sa svih uređaja',
      es: 'Cerrar sesion en todos los dispositivos',
      fr: 'Se deconnecter de tous les appareils',
      it: 'Esci da tutti i dispositivi',
    },
    notSet: {
      en: 'Not set',
      de: 'Nicht festgelegt',
      bs: 'Nije postavljeno',
      hr: 'Nije postavljeno',
      sr: 'Nije postavljeno',
      es: 'No configurado',
      fr: 'Non defini',
      it: 'Non impostato',
    },
    settingsLoadError: {
      en: 'Error loading settings.',
      de: 'Fehler beim Laden der Einstellungen.',
      bs: 'Greška pri učitavanju postavki.',
      hr: 'Greška pri učitavanju postavki.',
      sr: 'Greška pri učitavanju podešavanja.',
      es: 'Error al cargar la configuracion.',
      fr: 'Erreur lors du chargement des parametres.',
      it: 'Errore durante il caricamento impostazioni.',
    },
    notificationsSaved: {
      en: 'Notification settings saved.',
      de: 'Benachrichtigungseinstellungen gespeichert.',
      bs: 'Postavke obavijesti su sačuvane.',
      hr: 'Postavke obavijesti su spremljene.',
      sr: 'Podešavanja obaveštenja su sačuvana.',
      es: 'Notificaciones guardadas.',
      fr: 'Notifications enregistrees.',
      it: 'Notifiche salvate.',
    },
    notificationsSaveError: {
      en: 'Error saving notification settings.',
      de: 'Fehler beim Speichern der Benachrichtigungen.',
      bs: 'Greška pri spremanju postavki obavijesti.',
      hr: 'Greška pri spremanju postavki obavijesti.',
      sr: 'Greška pri čuvanju obaveštenja.',
      es: 'Error al guardar notificaciones.',
      fr: 'Erreur lors de enregistrement.',
      it: 'Errore durante il salvataggio.',
    },
    usernameRequired: {
      en: 'Username is required.',
      de: 'Benutzername ist erforderlich.',
      bs: 'Korisničko ime je obavezno.',
      hr: 'Korisničko ime je obavezno.',
      sr: 'Korisničko ime je obavezno.',
      es: 'El usuario es obligatorio.',
      fr: 'Nom utilisateur obligatoire.',
      it: 'Nome utente obbligatorio.',
    },
    usernameChanged: {
      en: 'Username changed successfully.',
      de: 'Benutzername erfolgreich geaendert.',
      bs: 'Korisničko ime je uspješno promijenjeno.',
      hr: 'Korisničko ime je uspješno promijenjeno.',
      sr: 'Korisničko ime je uspešno promenjeno.',
      es: 'Usuario cambiado correctamente.',
      fr: 'Nom utilisateur modifie.',
      it: 'Nome utente modificato.',
    },
    usernameChangeError: {
      en: 'Error changing username.',
      de: 'Fehler beim Aendern des Benutzernamens.',
      bs: 'Greška pri promjeni korisničkog imena.',
      hr: 'Greška pri promjeni korisničkog imena.',
      sr: 'Greška pri promeni korisničkog imena.',
      es: 'Error al cambiar usuario.',
      fr: 'Erreur lors du changement.',
      it: 'Errore durante la modifica.',
    },
    usernameTooShort: {
      en: 'Username is too short',
      de: 'Benutzername ist zu kurz',
      bs: 'Korisničko ime je nedovoljno dugo',
      hr: 'Korisničko ime je prekratko',
      sr: 'Korisničko ime je prekratko',
      es: 'El usuario es demasiado corto',
      fr: 'Nom utilisateur trop court',
      it: 'Nome utente troppo corto',
    },
    usernameNoSpaces: {
      en: 'Username cannot contain spaces',
      de: 'Benutzername darf keine Leerzeichen enthalten',
      bs: 'Korisničko ime ne smije sadržavati razmake',
      hr: 'Korisničko ime ne smije sadržavati razmake',
      sr: 'Korisničko ime ne sme sadržavati razmake',
      es: 'El usuario no puede contener espacios',
      fr: 'Nom utilisateur sans espaces',
      it: 'Nome utente senza spazi',
    },
    passwordTooShort: {
      en: 'Password is too short',
      de: 'Passwort ist zu kurz',
      bs: 'Lozinka je nedovoljno duga',
      hr: 'Lozinka je prekratka',
      sr: 'Lozinka je prekratka',
      es: 'La contrasena es demasiado corta',
      fr: 'Mot de passe trop court',
      it: 'Password troppo corta',
    },
    passwordStrength: {
      en: 'Password cannot contain spaces and must include a letter, number, and special character',
      de: 'Passwort darf keine Leerzeichen enthalten und muss Buchstaben, Zahlen und Sonderzeichen enthalten',
      bs: 'Lozinka ne smije imati razmake i mora sadržavati slovo, broj i specijalni znak',
      hr: 'Lozinka ne smije imati razmake i mora sadržavati slovo, broj i poseban znak',
      sr: 'Lozinka ne sme imati razmake i mora sadržavati slovo, broj i specijalni znak',
      es: 'La contrasena no puede contener espacios y debe incluir letra, numero y caracter especial',
      fr: 'Mot de passe sans espaces avec lettre, chiffre et caractere special',
      it: 'Password senza spazi con lettera, numero e carattere speciale',
    },
    cancel: {
      en: 'Cancel',
      de: 'Abbrechen',
      bs: 'Otkaži',
      hr: 'Otkaži',
      sr: 'Otkaži',
      es: 'Cancelar',
      fr: 'Annuler',
      it: 'Annulla',
    },
    confirm: {
      en: 'Confirm',
      de: 'Bestaetigen',
      bs: 'Potvrdi',
      hr: 'Potvrdi',
      sr: 'Potvrdi',
      es: 'Confirmar',
      fr: 'Confirmer',
      it: 'Conferma',
    },
    edit: {
      en: 'Edit',
      de: 'Bearbeiten',
      bs: 'Uredi',
      hr: 'Uredi',
      sr: 'Uredi',
      es: 'Editar',
      fr: 'Modifier',
      it: 'Modifica',
    },
    editProfile: {
      en: 'Edit profile',
      de: 'Profil bearbeiten',
      bs: 'Uredi profil',
      hr: 'Uredi profil',
      sr: 'Uredi profil',
      es: 'Editar perfil',
      fr: 'Modifier le profil',
      it: 'Modifica profilo',
    },
    profilePicture: {
      en: 'Profile picture',
      de: 'Profilbild',
      bs: 'Profilna slika',
      hr: 'Profilna slika',
      sr: 'Profilna slika',
      es: 'Foto de perfil',
      fr: 'Photo de profil',
      it: 'Foto profilo',
    },
    removeProfilePicture: {
      en: 'Remove profile picture',
      de: 'Profilbild entfernen',
      bs: 'Ukloni profilnu sliku',
      hr: 'Ukloni profilnu sliku',
      sr: 'Ukloni profilnu sliku',
      es: 'Eliminar foto de perfil',
      fr: 'Supprimer la photo de profil',
      it: 'Rimuovi foto profilo',
    },
    location: {
      en: 'Location',
      de: 'Ort',
      bs: 'Lokacija',
      hr: 'Lokacija',
      sr: 'Lokacija',
      es: 'Ubicacion',
      fr: 'Emplacement',
      it: 'Posizione',
    },
    enterFullName: {
      en: 'Enter full name',
      de: 'Vor- und Nachname eingeben',
      bs: 'Unesite ime i prezime',
      hr: 'Unesite ime i prezime',
      sr: 'Unesite ime i prezime',
      es: 'Introduce el nombre completo',
      fr: 'Saisir le nom complet',
      it: 'Inserisci nome completo',
    },
    enterCity: {
      en: 'Enter city',
      de: 'Stadt eingeben',
      bs: 'Unesite grad',
      hr: 'Unesite grad',
      sr: 'Unesite grad',
      es: 'Introduce ciudad',
      fr: 'Saisir la ville',
      it: 'Inserisci citta',
    },
    wrongPhoneFormat: {
      en: 'Wrong phone number format.',
      de: 'Falsches Telefonnummerformat.',
      bs: 'Pogrešan format broja.',
      hr: 'Pogrešan format broja.',
      sr: 'Pogrešan format broja.',
      es: 'Formato de telefono incorrecto.',
      fr: 'Format de telephone incorrect.',
      it: 'Formato telefono errato.',
    },
    saveChanges: {
      en: 'Save changes',
      de: 'Aenderungen speichern',
      bs: 'Spremi promjene',
      hr: 'Spremi promjene',
      sr: 'Sačuvaj promene',
      es: 'Guardar cambios',
      fr: 'Enregistrer',
      it: 'Salva modifiche',
    },
    profileUpdated: {
      en: 'Profile updated successfully.',
      de: 'Profil erfolgreich aktualisiert.',
      bs: 'Profil je uspješno ažuriran.',
      hr: 'Profil je uspješno ažuriran.',
      sr: 'Profil je uspešno ažuriran.',
      es: 'Perfil actualizado correctamente.',
      fr: 'Profil mis a jour.',
      it: 'Profilo aggiornato.',
    },
    selectValidImage: {
      en: 'Select a valid image.',
      de: 'Waehlen Sie ein gueltiges Bild.',
      bs: 'Odaberite validnu sliku.',
      hr: 'Odaberite validnu sliku.',
      sr: 'Odaberite validnu sliku.',
      es: 'Selecciona una imagen valida.',
      fr: 'Selectionnez une image valide.',
      it: 'Seleziona una immagine valida.',
    },
    uploadImageError: {
      en: 'Error uploading image.',
      de: 'Fehler beim Hochladen des Bildes.',
      bs: 'Greška pri uploadu slike.',
      hr: 'Greška pri uploadu slike.',
      sr: 'Greška pri uploadu slike.',
      es: 'Error al subir la imagen.',
      fr: 'Erreur lors de envoi de image.',
      it: 'Errore durante il caricamento.',
    },
    unsavedChangesConfirm: {
      en: 'You have unsaved changes. Are you sure you want to leave this page?',
      de: 'Sie haben ungespeicherte Aenderungen. Diese Seite verlassen?',
      bs: 'Imate nespremljene promjene. Da li ste sigurni da želite napustiti ovu stranicu?',
      hr: 'Imate nespremljene promjene. Jeste li sigurni da želite napustiti ovu stranicu?',
      sr: 'Imate nesačuvane promene. Da li ste sigurni da želite napustiti ovu stranicu?',
      es: 'Tienes cambios sin guardar. Seguro que quieres salir de esta pagina?',
      fr: 'Vous avez des modifications non enregistrees. Voulez-vous quitter cette page?',
      it: 'Hai modifiche non salvate. Vuoi lasciare questa pagina?',
    },
    search: {
      en: 'Search',
      de: 'Suchen',
      bs: 'Pretraži',
      hr: 'Pretraži',
      sr: 'Pretraži',
      es: 'Buscar',
      fr: 'Rechercher',
      it: 'Cerca',
    },
    searchUsersTitle: {
      en: 'Search users',
      de: 'Benutzer suchen',
      bs: 'Pretraga korisnika',
      hr: 'Pretraga korisnika',
      sr: 'Pretraga korisnika',
      es: 'Buscar usuarios',
      fr: 'Rechercher des utilisateurs',
      it: 'Cerca utenti',
    },
    enterNameOrUsername: {
      en: 'Enter name or username',
      de: 'Name oder Benutzername eingeben',
      bs: 'Unesite ime ili korisničko ime',
      hr: 'Unesite ime ili korisničko ime',
      sr: 'Unesite ime ili korisničko ime',
      es: 'Introduce nombre o usuario',
      fr: 'Saisir nom ou identifiant',
      it: 'Inserisci nome o utente',
    },
    searchGroupsTitle: {
      en: 'Search groups',
      de: 'Gruppen suchen',
      bs: 'Pretraga grupa',
      hr: 'Pretraga grupa',
      sr: 'Pretraga grupa',
      es: 'Buscar grupos',
      fr: 'Rechercher des groupes',
      it: 'Cerca gruppi',
    },
    enterGroupName: {
      en: 'Enter group name',
      de: 'Gruppennamen eingeben',
      bs: 'Unesite naziv grupe',
      hr: 'Unesite naziv grupe',
      sr: 'Unesite naziv grupe',
      es: 'Introduce nombre del grupo',
      fr: 'Saisir le nom du groupe',
      it: 'Inserisci nome gruppo',
    },
    viewProfile: {
      en: 'View profile',
      de: 'Profil ansehen',
      bs: 'Pogledaj profil',
      hr: 'Pogledaj profil',
      sr: 'Pogledaj profil',
      es: 'Ver perfil',
      fr: 'Voir le profil',
      it: 'Vedi profilo',
    },
    addToGroup: {
      en: 'Add to group',
      de: 'Zur Gruppe hinzufuegen',
      bs: 'Dodaj u grupu',
      hr: 'Dodaj u grupu',
      sr: 'Dodaj u grupu',
      es: 'Agregar al grupo',
      fr: 'Ajouter au groupe',
      it: 'Aggiungi al gruppo',
    },
    sendMessage: {
      en: 'Send message',
      de: 'Nachricht senden',
      bs: 'Pošalji poruku',
      hr: 'Pošalji poruku',
      sr: 'Pošalji poruku',
      es: 'Enviar mensaje',
      fr: 'Envoyer un message',
      it: 'Invia messaggio',
    },
    message: {
      en: 'Message',
      de: 'Nachricht',
      bs: 'Poruka',
      hr: 'Poruka',
      sr: 'Poruka',
      es: 'Mensaje',
      fr: 'Message',
      it: 'Messaggio',
    },
    previous: {
      en: 'Previous',
      de: 'Zurueck',
      bs: 'Prethodna',
      hr: 'Prethodna',
      sr: 'Prethodna',
      es: 'Anterior',
      fr: 'Precedent',
      it: 'Precedente',
    },
    next: {
      en: 'Next',
      de: 'Weiter',
      bs: 'Sljedeća',
      hr: 'Sljedeća',
      sr: 'Sledeća',
      es: 'Siguiente',
      fr: 'Suivant',
      it: 'Successivo',
    },
    createGroup: {
      en: 'Create group',
      de: 'Gruppe erstellen',
      bs: 'Kreiraj grupu',
      hr: 'Kreiraj grupu',
      sr: 'Kreiraj grupu',
      es: 'Crear grupo',
      fr: 'Creer un groupe',
      it: 'Crea gruppo',
    },
    creating: {
      en: 'Creating...',
      de: 'Wird erstellt...',
      bs: 'Kreiranje...',
      hr: 'Kreiranje...',
      sr: 'Kreiranje...',
      es: 'Creando...',
      fr: 'Creation...',
      it: 'Creazione...',
    },
    editGroup: {
      en: 'Edit group',
      de: 'Gruppe bearbeiten',
      bs: 'Uredi grupu',
      hr: 'Uredi grupu',
      sr: 'Uredi grupu',
      es: 'Editar grupo',
      fr: 'Modifier le groupe',
      it: 'Modifica gruppo',
    },
    updateGroup: {
      en: 'Update group',
      de: 'Gruppe aktualisieren',
      bs: 'Ažuriraj grupu',
      hr: 'Ažuriraj grupu',
      sr: 'Ažuriraj grupu',
      es: 'Actualizar grupo',
      fr: 'Mettre a jour le groupe',
      it: 'Aggiorna gruppo',
    },
    updating: {
      en: 'Updating...',
      de: 'Wird aktualisiert...',
      bs: 'Ažuriranje...',
      hr: 'Ažuriranje...',
      sr: 'Ažuriranje...',
      es: 'Actualizando...',
      fr: 'Mise a jour...',
      it: 'Aggiornamento...',
    },
    groupImage: {
      en: 'Group image',
      de: 'Gruppenbild',
      bs: 'Slika grupe',
      hr: 'Slika grupe',
      sr: 'Slika grupe',
      es: 'Imagen del grupo',
      fr: 'Image du groupe',
      it: 'Immagine gruppo',
    },
    removeImage: {
      en: 'Remove image',
      de: 'Bild entfernen',
      bs: 'Ukloni sliku',
      hr: 'Ukloni sliku',
      sr: 'Ukloni sliku',
      es: 'Eliminar imagen',
      fr: 'Supprimer image',
      it: 'Rimuovi immagine',
    },
    groupName: {
      en: 'Group name',
      de: 'Gruppenname',
      bs: 'Naziv grupe',
      hr: 'Naziv grupe',
      sr: 'Naziv grupe',
      es: 'Nombre del grupo',
      fr: 'Nom du groupe',
      it: 'Nome gruppo',
    },
    description: {
      en: 'Description',
      de: 'Beschreibung',
      bs: 'Opis',
      hr: 'Opis',
      sr: 'Opis',
      es: 'Descripcion',
      fr: 'Description',
      it: 'Descrizione',
    },
    createGroupError: {
      en: 'An error occurred while creating the group.',
      de: 'Beim Erstellen der Gruppe ist ein Fehler aufgetreten.',
      bs: 'Došlo je do greške prilikom kreiranja grupe.',
      hr: 'Došlo je do greške prilikom kreiranja grupe.',
      sr: 'Došlo je do greške prilikom kreiranja grupe.',
      es: 'Ocurrio un error al crear el grupo.',
      fr: 'Une erreur est survenue lors de la creation du groupe.',
      it: 'Errore durante la creazione del gruppo.',
    },
    updateGroupError: {
      en: 'An error occurred while updating the group.',
      de: 'Beim Aktualisieren der Gruppe ist ein Fehler aufgetreten.',
      bs: 'Došlo je do greške prilikom ažuriranja grupe.',
      hr: 'Došlo je do greške prilikom ažuriranja grupe.',
      sr: 'Došlo je do greške prilikom ažuriranja grupe.',
      es: 'Ocurrio un error al actualizar el grupo.',
      fr: 'Une erreur est survenue lors de la mise a jour du groupe.',
      it: 'Errore durante aggiornamento del gruppo.',
    },
    viewGroup: {
      en: 'View group',
      de: 'Gruppe ansehen',
      bs: 'Pogledaj grupu',
      hr: 'Pogledaj grupu',
      sr: 'Pogledaj grupu',
      es: 'Ver grupo',
      fr: 'Voir le groupe',
      it: 'Vedi gruppo',
    },
    requestJoinGroup: {
      en: 'Send request to join group',
      de: 'Anfrage zum Beitritt senden',
      bs: 'Pošalji zahtjev za pridruživanje grupi',
      hr: 'Pošalji zahtjev za pridruživanje grupi',
      sr: 'Pošalji zahtev za pridruživanje grupi',
      es: 'Enviar solicitud para unirse al grupo',
      fr: 'Envoyer une demande pour rejoindre le groupe',
      it: 'Invia richiesta di adesione',
    },
    myGroups: {
      en: 'My groups',
      de: 'Meine Gruppen',
      bs: 'Moje grupe',
      hr: 'Moje grupe',
      sr: 'Moje grupe',
      es: 'Mis grupos',
      fr: 'Mes groupes',
      it: 'I miei gruppi',
    },
    memberships: {
      en: 'Memberships',
      de: 'Mitgliedschaften',
      bs: 'Članstva',
      hr: 'Članstva',
      sr: 'Članstva',
      es: 'Membresias',
      fr: 'Adhesions',
      it: 'Iscrizioni',
    },
    members: {
      en: 'members',
      de: 'Mitglieder',
      bs: 'članova',
      hr: 'članova',
      sr: 'članova',
      es: 'miembros',
      fr: 'membres',
      it: 'membri',
    },
    noMembers: {
      en: 'No members',
      de: 'Keine Mitglieder',
      bs: 'Nema članova',
      hr: 'Nema članova',
      sr: 'Nema članova',
      es: 'Sin miembros',
      fr: 'Aucun membre',
      it: 'Nessun membro',
    },
    noAdminGroups: {
      en: 'You have not created any groups',
      de: 'Sie haben keine Gruppen erstellt',
      bs: 'Nemate napravljenih grupa',
      hr: 'Nemate napravljenih grupa',
      sr: 'Nemate napravljenih grupa',
      es: 'No has creado grupos',
      fr: 'Vous navez cree aucun groupe',
      it: 'Non hai creato gruppi',
    },
    noMemberGroups: {
      en: 'You are not a member of any group',
      de: 'Sie sind in keiner Gruppe Mitglied',
      bs: 'Niste član nijedne grupe',
      hr: 'Niste član nijedne grupe',
      sr: 'Niste član nijedne grupe',
      es: 'No eres miembro de ningun grupo',
      fr: 'Vous netes membre daucun groupe',
      it: 'Non sei membro di alcun gruppo',
    },
    findUsers: {
      en: 'Find people to play sports with',
      de: 'Finden Sie Leute fuer Sporttermine',
      bs: 'Pronađite ljude za sportske termine',
      hr: 'Pronađite ljude za sportske termine',
      sr: 'Pronađite ljude za sportske termine',
      es: 'Encuentra personas para hacer deporte',
      fr: 'Trouvez des personnes pour faire du sport',
      it: 'Trova persone per fare sport',
    },
    searchUsers: {
      en: 'Search users',
      de: 'Benutzer suchen',
      bs: 'Pretraži korisnike',
      hr: 'Pretraži korisnike',
      sr: 'Pretraži korisnike',
      es: 'Buscar usuarios',
      fr: 'Rechercher des utilisateurs',
      it: 'Cerca utenti',
    },
    toggleNavigation: {
      en: 'Toggle navigation',
      de: 'Navigation umschalten',
      bs: 'Otvori ili zatvori navigaciju',
      hr: 'Otvori ili zatvori navigaciju',
      sr: 'Otvori ili zatvori navigaciju',
      es: 'Alternar navegacion',
      fr: 'Basculer la navigation',
      it: 'Attiva navigazione',
    },
    loading: {
      en: 'Loading...',
      de: 'Laden...',
      bs: 'Učitavanje...',
      hr: 'Učitavanje...',
      sr: 'Učitavanje...',
      es: 'Cargando...',
      fr: 'Chargement...',
      it: 'Caricamento...',
    },
  };

  get currentLanguage(): LanguageCode {
    return this.languageSubject.value;
  }

  setLanguage(language: string): void {
    const languageCode = this.isSupportedLanguage(language)
      ? language
      : this.defaultLanguage;

    localStorage.setItem('appLanguage', languageCode);
    document.documentElement.lang = languageCode;
    this.languageSubject.next(languageCode);
  }

  translate(key: string): string {
    return (
      this.translations[key]?.[this.currentLanguage] ||
      this.translations[key]?.[this.defaultLanguage] ||
      key
    );
  }

  getLanguageName(code: string): string {
    return (
      this.languages.find((language) => language.code === code)?.name ||
      this.languages.find((language) => language.code === this.defaultLanguage)!.name
    );
  }

  private getSavedLanguage(): LanguageCode {
    const savedLanguage = localStorage.getItem('appLanguage');
    return this.isSupportedLanguage(savedLanguage)
      ? savedLanguage
      : this.defaultLanguage;
  }

  private isSupportedLanguage(language: string | null): language is LanguageCode {
    return ['en', 'de', 'bs', 'hr', 'sr', 'es', 'fr', 'it'].includes(
      language || '',
    );
  }
}
